---
title: "Simulations_exponent"
output: html_document
date: "2025-03-10"
---

```{r simulated alpha freqs}

library(ggplot2)
library(dplyr)

data= read.csv('~/Documents/McGill/simulations4Giu/Simulations_frequency_output.csv', header = TRUE)
data=data[501:4500,]

corrspec = read.csv('~/Documents/McGill/simulations4Giu/Frequency_Simulations_corrspec.csv', header = FALSE)
corrspec=corrspec[501:4500,]

corrspec_error = read.csv('~/Documents/McGill/simulations4Giu/Frequency_Simulations_error.csv', header = FALSE)
corrspec_error=corrspec_error[501:4500,]

corrspeclinear = read.csv('~/Documents/McGill/simulations4Giu/Frequency_Simulations_corrspec_linear.csv', header = FALSE)
corrspeclinear=corrspeclinear[501:4500,]

data$expon_error= data$expon_BIC-1

data$corrspec_error= rowMeans(corrspec_error)

data$Var1 = factor(data$Var1)

jitter_pos=position_jitter(width = .15, height = 0, seed = 1)
ggplot(data, aes(x=Var1, y=expon_BIC, group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5, position= jitter_pos) + theme_classic() + xlab("simulated alpha frequency") + ylab("estimated arrhythmic slope")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_hline(yintercept = 1, linetype= 'dashed')

ggsave('~/Desktop/alertness_2023/Figures/Simulated_frequencies_scatter_plot.pdf', device = "pdf", width= 10, height =5)

jitter_pos=position_jitter(width = .15, height = 0, seed = 1)
ggplot(data, aes(x=Var1, y=mse_BIC, group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5, position= jitter_pos) + theme_classic() + xlab("simulated alpha frequency") + ylab("residual variance (a.u.)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') 


ggplot(data, aes(x=Var1, y=expon_BIC, group=Var1, fill = 'Var1', colour = 'Var1'))+  ggdist::stat_halfeye(adjust = .5, width = .5, .width = 0, justification = -.5, alpha=0.5, point_alpha= 0) + geom_boxplot(width = .15, outlier.shape = NA, colour= '#202020', position = position_dodge(1)) + theme_classic() + xlab("simulated alpha frequency") + ylab("estimated arrhythmic slope")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_hline(yintercept = 1, linetype= 'dashed') + coord_cartesian(ylim = c(0.7, 1.3)) + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_color_manual(values=c('#10A0C0', '#D97D08'))

ggsave('~/Desktop/alertness_2023/Figures/Simulated_frequencies_boxplot_plot.pdf', device = "pdf", width= 10, height =5)


ggplot(data, aes(x=Var1, y=mse_BIC, group=Var1, fill = 'Var1', colour = 'Var1'))+  ggdist::stat_halfeye(adjust = .5, width = .5, .width = 0, justification = -.5, alpha=0.5, point_alpha= 0) + geom_boxplot(width = .15, outlier.shape = NA, colour= '#202020', position = position_dodge(1)) + theme_classic() + xlab("residual variance (a.u.)") + ylab("estimated arrhythmic slope")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')  + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_color_manual(values=c('#10A0C0', '#D97D08'))

ggsave('~/Desktop/alertness_2023/Figures/Simulated_frequencies_boxplot_MSE.pdf', device = "pdf", width= 10, height =5)

ggplot(data, aes(x=Var1, y=expon_error, group=Var1, fill = 'Var1', colour = 'Var1'))+  ggdist::stat_halfeye(adjust = .5, width = .5, .width = 0, justification = -.5, alpha=0.5, point_alpha= 0) + geom_boxplot(width = .15, outlier.shape = NA, colour= '#202020', position = position_dodge(1)) + theme_classic() + xlab("simulated center peak frequency") + ylab("error in estimated arrhythmic slope")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')  + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_color_manual(values=c('#10A0C0', '#D97D08')) + coord_cartesian(ylim = c(-0.5,0.5))

ggsave('~/Desktop/alertness_2023/Figures/Simulated_frequencies_boxplot_error_expon.pdf', device = "pdf", width= 10, height =5)


# corr plot between corr spec and the exponent 
# tt(22:36)

corrspecLinear= read.csv('~/Documents/McGill/simulations4Giu/Frequency_Simulations_corrspec_linear.csv', header = FALSE)
corrspecLinear=corrspecLinear[501:4500,]

data= read.csv('~/Documents/McGill/simulations4Giu/Simulations_frequency_output.csv', header = TRUE)
data=data[501:4500,]
data$corralpha=rowMeans(corrspec[,22:36])
data$corrspec_error= rowMeans(corrspec_error)
data$corralphalinear=rowMeans(corrspecLinear[,22:36])
data$alpha_amplitude= data$Var1-6
data$expon_error= (data$expon_BIC-1)^2

# add in column for beta even though we do not simulate changes 
data$corrbeta=rowMeans(corrspec[,37:73])
data$corrbetalinear=rowMeans(corrspecLinear[,37:73])

peak_params_cf= read.csv('~/Documents/McGill/simulations4Giu/Simulations_frequency_peaks_centerFreq.csv', header = FALSE)
peak_params_cf=peak_params_cf[501:4500,]
peak_params_amp= read.csv('~/Documents/McGill/simulations4Giu/Simulations_frequency_peaks_amplitude.csv', header = FALSE)
peak_params_amp=peak_params_amp[501:4500,]

peak_params_cf= as.matrix(peak_params_cf)
peak_params_amp= as.matrix(peak_params_amp)

peak_params_amp[which(peak_params_cf <5 | peak_params_cf >15)] = NaN
peak_params_cf[which(peak_params_cf <5 | peak_params_cf >15)] = NaN

data$corralphamodel=apply(peak_params_amp, 1,max,na.rm = TRUE)
data$corralphamodel[data$corralphamodel== -Inf] =NaN

peak_params_cf= read.csv('~/Documents/McGill/simulations4Giu/Simulations_amplitude_peaks_centerFreq.csv', header = FALSE)
peak_params_cf=peak_params_cf[501:4500,]
peak_params_amp= read.csv('~/Documents/McGill/simulations4Giu/Simulations_amplitude_peaks_amplitude.csv', header = FALSE)
peak_params_amp=peak_params_amp[501:4500,]

peak_params_cf= as.matrix(peak_params_cf)
peak_params_amp= as.matrix(peak_params_amp)

peak_params_amp[which(peak_params_cf <14 | peak_params_cf >30)] = NaN
peak_params_cf[which(peak_params_cf <14 | peak_params_cf >30)] = NaN

data$corrbetamodel=apply(peak_params_amp, 1,max,na.rm = TRUE)
data$corrbetamodel[data$corrbetamodel== -Inf] =NaN

data$corralphamodel_error= (data$corralphamodel-0.7)^2
data$expon_error=data$expon_BIC-1


ggplot(data, aes(x=log10(corrspec_error), y=expon_error))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in rhythmic component") + ylab("error in arrhythmic slope")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_hline(yintercept = 0, linetype= 'dashed') + stat_smooth(data= data[data$expon_error >0,], aes(x=log10(corrspec_error), y=expon_error), method = "glm",formula = y ~ poly(x, 1),fullrange = FALSE, color= 'black', linetype='dashed', se = FALSE)+ stat_smooth(data= data[data$expon_error <0,], aes(x=log10(corrspec_error), y=expon_error) , method = "glm",formula = y ~ poly(x, 1),fullrange = FALSE, color= 'black', linetype='dashed', se= FALSE)

ggsave('~/Desktop/alertness_2023/Figures/Simulated_frequency_scatter_plot_two_types_of_error.pdf', device = "pdf", width= 5, height =5)

ggplot(data, aes(x=log10(corralphamodel_error), y=expon_error, group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in rhythmic component") + ylab("error in arrhythmic slope")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_hline(yintercept = 0, linetype= 'dashed')

ggsave('~/Desktop/alertness_2023/Figures/Simulated_frequency_scatter_plot_two_types_of_error_modelled.pdf', device = "pdf", width= 5, height =5)

DescTools::SpearmanRho(data$corralpha, data$corralphalinear, use = c("complete.obs"), conf.level = 0.95) # 0.9783963

# remove bad estimates 
data2= data[abs(data$mse_BIC) < 3*sd(data$mse_BIC) + mean(data$mse_BIC) ,]
corrspec2= corrspec[abs(data$mse_BIC) < 3*sd(data$mse_BIC) + mean(data$mse_BIC)   ,]
corrspec2= corrspec2[data2$expon_BIC > 0.5 & data2$expon_BIC < 1.5  ,]
data2= data2[data2$expon_BIC > 0.5 & data2$expon_BIC < 1.5 ,]

DescTools::SpearmanRho(data2$expon_BIC, rowMeans(corrspec2[,22:36]), use = c("complete.obs"), conf.level = 0.95) # -0.2962450
DescTools::SpearmanRho(data2$expon_BIC, data2$corralphamodel, use = c("complete.obs"), conf.level = 0.95) # -0.01882922
DescTools::SpearmanRho(data2$expon_BIC, data2$corralphalinear, use = c("complete.obs"), conf.level = 0.95) # -0.1675251








ggplot(data2, aes(x=log10(abs(expon_error)), y=corralpha, group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in exponent") + ylab("corrected alpha power (log-log)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = log10(0), linetype= 'dashed') + geom_hline(yintercept = 0.7, linetype= 'dashed') + facet_wrap(~Var1, nrow = 2, scales = "free") + stat_smooth(method = "lm", formula = y ~ poly(x, 1), se = TRUE,fullrange = FALSE, color= 'black') + coord_cartesian(xlim = c(-4, 0), ylim = c(0.1, 0.9))

ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_scatter_error_power_relationship_by_simulated_exponent.pdf', device = "pdf", width= 10, height =5)

ggplot(data2, aes(x=log10(abs(expon_error)), y=corralpha))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in exponent") + ylab("corrected alpha power (log-log)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = log10(0), linetype= 'dashed') + geom_hline(yintercept = 0.7, linetype= 'dashed') +  stat_smooth(method = "lm", formula = y ~ poly(x, 1), se = TRUE,fullrange = FALSE, color= 'black')  + coord_cartesian(xlim = c(-4, 0), ylim = c(0.1, 1.75))

ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_scatter_error_power_relationship_by_simulated_exponent.pdf', device = "pdf", width= 5, height =5)


ggplot(data2, aes(x=log10(abs(expon_error)), y=log10(corralphamodel)))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in exponent") + ylab("modelled power (log-log)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = log10(0), linetype= 'dashed') + geom_hline(yintercept = log10(0.7), linetype= 'dashed') +  stat_smooth(method = "lm", formula = y ~ poly(x, 1), se = TRUE,fullrange = FALSE, color= 'black')  + coord_cartesian(xlim = c(-4, 0), ylim = c(-0.7, 0.3))

ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_scatter_error_MODELLED_power_relationship_by_simulated_exponent.pdf', device = "pdf", width= 5, height =5)

ggplot(data2[abs(data2$expon_error) < 0.05,], aes(x=corralphamodel, y=corralpha))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in exponent") + ylab("corrected alpha power (log-log)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = log10(0), linetype= 'dashed') + geom_hline(yintercept = 0.7, linetype= 'dashed') +  stat_smooth(method = "lm", formula = y ~ poly(x, 1), se = TRUE,fullrange = FALSE, color= 'black') 


ggplot(data2[abs(data2$expon_error) > 0.05,], aes(x=corralphamodel, y=corralpha))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in exponent") + ylab("corrected alpha power (log-log)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = log10(0), linetype= 'dashed') + geom_hline(yintercept = 0.7, linetype= 'dashed') +  stat_smooth(method = "lm", formula = y ~ poly(x, 1), se = TRUE,fullrange = FALSE, color= 'black') 


DescTools::SpearmanRho(data2$corralpha[data2$Var1 == 10], data2$expon_error[data2$Var1 == 10], use = c("complete.obs"), conf.level = 0.95) 

DescTools::SpearmanRho(data2$corralpha[abs(data2$expon_error) > 0.05], data2$corralphamodel[abs(data2$expon_error) > 0.05], use = c("complete.obs"), conf.level = 0.95) 

DescTools::SpearmanRho(data2$corralpha[abs(data2$expon_error) < 0.05], data2$corralphamodel[abs(data2$expon_error) < 0.05], use = c("complete.obs"), conf.level = 0.95) 

datareg= as.data.frame(scale(data2))
lm1=lm(corralphamodel ~  corralpha , datareg)
lm2=lm(corralphamodel ~  corralpha +expon_error, datareg)
lm3=lm(corralphamodel ~  corralpha* expon_error, datareg)
anova(lm1,lm2,lm3)
BIC(lm3) - BIC(lm2)
sjPlot::tab_model(lm2)


# partial correlations
cor.test(datareg$corralpha , datareg$expon_BIC, method= 'spearman')

cor.test(residuals(lm(datareg$corralpha ~ datareg$expon_error)), datareg$expon_BIC, method= 'spearman')

cor.test(datareg$corralpha, datareg$expon_error, method= 'spearman')
cor.test(datareg$corralpha, datareg$expon_BIC, method= 'spearman')

# mediation analysis
datareg=data2
datareg$corralpha = log10(datareg$corralpha)
datareg$expon_BIC = log10(datareg$expon_BIC)
#datareg$expon_error = log10(abs(datareg$expon_error))





datareg$expon_error = log10(abs(datareg$expon_error))
datareg= as.data.frame(scale(datareg))
fit.totaleffect=lm(corralpha~expon_BIC, datareg)
summary(fit.totaleffect)
sjPlot::tab_model(fit.totaleffect)

fit.mediator=lm(expon_error~expon_BIC, datareg)
summary(fit.mediator)
sjPlot::tab_model(fit.mediator)

fit.dv=lm(corralpha~expon_error+expon_BIC,datareg)
summary(fit.dv)
sjPlot::tab_model(fit.dv)

results = mediation::mediate(fit.mediator, fit.dv, treat='expon_BIC', mediator='expon_error', boot=T)
summary(results)

signif(fit.mediator$coefficients[2],2)
signif(fit.dv$coefficients[2],2)
signif(results$tau.coef,2)
signif(fit.dv$coefficients[3],2)

pdf("~/Desktop/Xiaobo_age_data/mediation_of_age_on_spectral_flow_direction.pdf")
data <- c(0, "'.-17*'", 0,
          0, 0, 0, 
          "'-.24*'", "'.39* (.35)'", 0)
M<- matrix (nrow=3, ncol=3, byrow = TRUE, data=data)
plot<- plotmat (M, pos=c(1,2), 
                name= c( "Theta \nbottom-up","Age", "Beta \ntop-down"), 
                box.type = "circle", box.size = 0.12, box.prop=0.5,  curve=0)
dev.off()









spr2=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==7], rowMeans(corrspec2[data2$Var1==7,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==8], rowMeans(corrspec2[data2$Var1==8,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==9], rowMeans(corrspec2[data2$Var1==9,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==10], rowMeans(corrspec2[data2$Var1==10,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==11], rowMeans(corrspec2[data2$Var1==11,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==12], rowMeans(corrspec2[data2$Var1==12,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==13], rowMeans(corrspec2[data2$Var1==13,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==14], rowMeans(corrspec2[data2$Var1==14,22:36]), use = c("complete.obs"), conf.level = 0.95) 


data4plot=data.frame(freqs= c(7,8,9,10,11,12,13,14),
                     corrs=c( spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]]), 
                     lower=c(spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]]), 
                     upper=c(spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]]))


ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill='1')) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_alpha_slope_by_simulated_frequency.pdf', device = "pdf", height = 5, width = 5)

data4plot2=data4plot

spr2=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==7], data2$corralphamodel[data2$Var1==7], use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==8], data2$corralphamodel[data2$Var1==8], use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==9], data2$corralphamodel[data2$Var1==9], use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==10], data2$corralphamodel[data2$Var1==10], use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==11], data2$corralphamodel[data2$Var1==11], use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==12], data2$corralphamodel[data2$Var1==12], use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==13], data2$corralphamodel[data2$Var1==13], use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==14], data2$corralphamodel[data2$Var1==14], use = c("complete.obs"), conf.level = 0.95) 


data4plot=data.frame(freqs= c(7,8,9,10,11,12,13,14),
                     corrs=c( spr2[[1]],spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]]), 
                     lower=c( spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]]), 
                     upper=c( spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]]),
                     nototals= c(sum(is.na(data2$corralphamodel[data2$Var1==7]))/length(data2$corralphamodel[data2$Var1==7]),
                                 sum(is.na(data2$corralphamodel[data2$Var1==8]))/length(data2$corralphamodel[data2$Var1==8]),
                                 sum(is.na(data2$corralphamodel[data2$Var1==9]))/length(data2$corralphamodel[data2$Var1==9]),sum(is.na(data2$corralphamodel[data2$Var1==10]))/length(data2$corralphamodel[data2$Var1==10]),
                     sum(is.na(data2$corralphamodel[data2$Var1==11]))/length(data2$corralphamodel[data2$Var1==11]),
                     sum(is.na(data2$corralphamodel[data2$Var1==12]))/length(data2$corralphamodel[data2$Var1==12]),
                     sum(is.na(data2$corralphamodel[data2$Var1==13]))/length(data2$corralphamodel[data2$Var1==13]),
                     sum(is.na(data2$corralphamodel[data2$Var1==14]))/length(data2$corralphamodel[data2$Var1==14])))


data4plot3=data4plot
data4plot$nototals= data4plot$nototals+0.000001
ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= -1*log10(100*nototals), fill= -1*log10(100*nototals))) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2()   + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14)) + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white")+ geom_point( size=5)

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_alpha_slope_by_simulated_frequency_modeled_params.pdf', device = "pdf", height = 5, width = 8)

data4plot2$nototals =0
data4plot=rbind(data4plot2, data4plot)
data4plot$type= rep(c('subtraction', 'model'), each =8)

data4plot$nototals= data4plot$nototals+0.000001
ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= -1*log10(100*nototals), fill= -1*log10(100*nototals))) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2()   + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14)) + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white")+ geom_point( size=5) + facet_wrap(~type)

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_alpha_slope_by_simulated_frequency_comparison_alpha_method.pdf', device = "pdf", height = 5, width = 15)


ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= -1*log10(100*nototals), fill= -1*log10(100*nototals))) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2()   + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14)) + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white")+ geom_point( size=5) + facet_wrap(~type) + geom_hline(yintercept = c(-0.15, 0.15), linetype= 'dashed')

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_alpha_slope_by_simulated_frequency_comparison_alpha_method.pdf', device = "pdf", height = 5, width = 15)

data4plot4= data4plot

spr2=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==7], data2$corralphalinear[data2$Var1==7], use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==8], data2$corralphalinear[data2$Var1==8], use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==9], data2$corralphalinear[data2$Var1==9], use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==10], data2$corralphalinear[data2$Var1==10], use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==11], data2$corralphalinear[data2$Var1==11], use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==12], data2$corralphalinear[data2$Var1==12], use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==13], data2$corralphalinear[data2$Var1==13], use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==14], data2$corralphalinear[data2$Var1==14], use = c("complete.obs"), conf.level = 0.95) 


data4plot=data.frame(freqs= c(7,8,9,10,11,12,13,14),
                     corrs=c( spr2[[1]],spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]]), 
                     lower=c( spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]]), 
                     upper=c( spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]]))


ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill='1')) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated rhythmic alpha frequenyc (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_alpha_slope_by_simulated_linearspace_frequency.pdf', device = "pdf", height = 5, width = 5)


data4plot$nototals =0
data4plot$type = 'linear'
data4plot=rbind(data4plot4, data4plot)
data4plot$type = factor(data4plot$type, levels = c('model', 'subtraction', 'linear'))

ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill= '1')) +
    ggpubr::theme_classic2()   + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white")+ geom_point( size=5) + facet_wrap(~type) + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + geom_hline(yintercept = c(-0.15, 0.15), linetype= 'dashed')

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_alpha_slope_by_simulated_frequency_model_no_NAs_compare_all.pdf', device = "pdf", height = 5, width = 15)








data2$corralphamodel[is.na(data2$corralphamodel)] =0
spr2=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==7], data2$corralphamodel[data2$Var1==7], use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==8], data2$corralphamodel[data2$Var1==8], use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==9], data2$corralphamodel[data2$Var1==9], use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==10], data2$corralphamodel[data2$Var1==10], use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==11], data2$corralphamodel[data2$Var1==11], use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==12], data2$corralphamodel[data2$Var1==12], use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==13], data2$corralphamodel[data2$Var1==13], use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==14], data2$corralphamodel[data2$Var1==14], use = c("complete.obs"), conf.level = 0.95) 

data4plot=data.frame(freqs= c(7,8,9,10,11,12,13,14),
                     corrs=c( spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]]), 
                     lower=c(spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]]), 
                     upper=c(spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]]))


ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill='1')) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_alpha_slope_by_simulated_frequency_model_no_NAs.pdf', device = "pdf", height = 5, width = 5)

data4plot$nototals =0
data4plot=rbind(data4plot3, data4plot)
data4plot$type= rep(c('NaNs included', 'NaNs replaced'), each =8)

ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill= '1')) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2()   + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white")+ geom_point( size=5) + facet_wrap(~type) + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08'))

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_alpha_slope_by_simulated_frequency_model_no_NAs_compare.pdf', device = "pdf", height = 5, width = 5)





# look at relationship with beta 
spr2=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==7], rowMeans(corrspec2[data2$Var1==7,37:73]), use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==8], rowMeans(corrspec2[data2$Var1==8,37:73]), use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==9], rowMeans(corrspec2[data2$Var1==9,37:73]), use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==10], rowMeans(corrspec2[data2$Var1==10,37:73]), use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==11], rowMeans(corrspec2[data2$Var1==11,37:73]), use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==12], rowMeans(corrspec2[data2$Var1==12,37:73]), use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==13], rowMeans(corrspec2[data2$Var1==13,37:73]), use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==14], rowMeans(corrspec2[data2$Var1==14,37:73]), use = c("complete.obs"), conf.level = 0.95) 


data4plot=data.frame(freqs= c(7,8,9,10,11,12,13,14),
                     corrs=c( spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]]), 
                     lower=c(spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]]), 
                     upper=c(spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]]))


ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill='1')) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship w/ beta power (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_beta_slope_by_simulated_frequency.pdf', device = "pdf", height = 5, width = 5)


spr2=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==7], data2$corrbetamodel[data2$Var1==7], use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==8], data2$corrbetamodel[data2$Var1==8], use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==9], data2$corrbetamodel[data2$Var1==9], use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==10], data2$corrbetamodel[data2$Var1==10], use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==11], data2$corrbetamodel[data2$Var1==11], use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==12], data2$corrbetamodel[data2$Var1==12], use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==13], data2$corrbetamodel[data2$Var1==13], use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==14], data2$corrbetamodel[data2$Var1==14], use = c("complete.obs"), conf.level = 0.95) 


data4plot=data.frame(freqs= c(7,8,9,10,11,12,13,14),
                     corrs=c( spr2[[1]],spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]]), 
                     lower=c( spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]]), 
                     upper=c( spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]]),
                     nototals= c(sum(is.na(data2$corrbetamodel[data2$Var1==7]))/length(data2$corrbetamodel[data2$Var1==7]),
                                 sum(is.na(data2$corrbetamodel[data2$Var1==8]))/length(data2$corrbetamodel[data2$Var1==8]),
                                 sum(is.na(data2$corrbetamodel[data2$Var1==9]))/length(data2$corrbetamodel[data2$Var1==9]),sum(is.na(data2$corrbetamodel[data2$Var1==10]))/length(data2$corrbetamodel[data2$Var1==10]),
                     sum(is.na(data2$corrbetamodel[data2$Var1==11]))/length(data2$corrbetamodel[data2$Var1==11]),
                     sum(is.na(data2$corrbetamodel[data2$Var1==12]))/length(data2$corrbetamodel[data2$Var1==12]),
                     sum(is.na(data2$corrbetamodel[data2$Var1==13]))/length(data2$corrbetamodel[data2$Var1==13]),
                     sum(is.na(data2$corrbetamodel[data2$Var1==14]))/length(data2$corrbetamodel[data2$Var1==14])))


data4plot$nototals= data4plot$nototals+0.000001
ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= -1*log10(100*nototals), fill= -1*log10(100*nototals))) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2()   + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14)) + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white")+ geom_point( size=5)

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_beta_slope_by_simulated_frequency_modeled_params.pdf', device = "pdf", height = 5, width = 8)



spr2=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==7], data2$corrbetalinear[data2$Var1==7], use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==8], data2$corrbetalinear[data2$Var1==8], use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==9], data2$corrbetalinear[data2$Var1==9], use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==10], data2$corrbetalinear[data2$Var1==10], use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==11], data2$corrbetalinear[data2$Var1==11], use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==12], data2$corrbetalinear[data2$Var1==12], use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==13], data2$corrbetalinear[data2$Var1==13], use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==14], data2$corrbetalinear[data2$Var1==14], use = c("complete.obs"), conf.level = 0.95) 


data4plot=data.frame(freqs= c(7,8,9,10,11,12,13,14),
                     corrs=c( spr2[[1]],spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]]), 
                     lower=c( spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]]), 
                     upper=c( spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]]))


ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill='1')) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated rhythmic alpha frequenyc (Hz)") + ylab("estimated relationship w/ beta (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_beta_slope_by_simulated_linearspace_frequency.pdf', device = "pdf", height = 5, width = 5)




spr2=DescTools::SpearmanRho(data2$corralphalinear[data2$Var1==7], data2$corrbetalinear[data2$Var1==7], use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$corralphalinear[data2$Var1==8], data2$corrbetalinear[data2$Var1==8], use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$corralphalinear[data2$Var1==9], data2$corrbetalinear[data2$Var1==9], use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$corralphalinear[data2$Var1==10], data2$corrbetalinear[data2$Var1==10], use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$corralphalinear[data2$Var1==11], data2$corrbetalinear[data2$Var1==11], use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$corralphalinear[data2$Var1==12], data2$corrbetalinear[data2$Var1==12], use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$corralphalinear[data2$Var1==13], data2$corrbetalinear[data2$Var1==13], use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$corralphalinear[data2$Var1==14], data2$corrbetalinear[data2$Var1==14], use = c("complete.obs"), conf.level = 0.95) 

data4plot=data.frame(freqs= c(7,8,9,10,11,12,13,14),
                     corrs=c( spr2[[1]],spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]]), 
                     lower=c( spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]]), 
                     upper=c( spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]]))


ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill='1')) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated rhythmic alpha frequenyc (Hz)") + ylab("estimated relationship w/ beta (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')
```



```{r simulated alpha amplitudes}

library(ggplot2)
library(dplyr)

data= read.csv('~/Documents/McGill/simulations4Giu/Simulations_amplitudes_output.csv', header = TRUE)

corrspec = read.csv('~/Documents/McGill/simulations4Giu/Amplitude_Simulations_corrspec.csv', header = FALSE)

corrspecLinear = read.csv('~/Documents/McGill/simulations4Giu/Amplitude_Simulations_corrspec_linear.csv', header = FALSE)

corrspec_error = read.csv('~/Documents/McGill/simulations4Giu/Amplitude_Simulations_error.csv', header = FALSE)

cor.test(data$expon_BIC, data$Var1) # 0.06803241
cor.test(data$mse_BIC, data$Var1) # -0.1858279

data$expon_error= (data$expon_BIC-1)
data$corrspec_error= rowMeans(corrspec_error)
cor.test(data$corrspec_error, data$Var1) # -0.001683254

data$Var1 = factor(data$Var1)


jitter_pos=position_jitter(width = .25, height = 0, seed = 1)
ggplot(data, aes(x=Var1, y=expon_BIC, group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5, position= jitter_pos) + theme_classic() + xlab("simulated alpha amplitude") + ylab("estimated arrhythmic slope")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_hline(yintercept = 1, linetype= 'dashed')

ggsave('~/Desktop/alertness_2023/Figures/Simulated_amplitude_scatter_plot.pdf', device = "pdf", width= 10, height =5)


ggplot(data, aes(x=log10(corrspec_error), y=expon_error, group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in rhythmic component") + ylab("error in arrhythmic slope")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_hline(yintercept = 0, linetype= 'dashed') + facet_wrap(~Var1, ncol = 5)

ggsave('~/Desktop/alertness_2023/Figures/Simulated_amplitudes_scatter_plot_two_types_of_error_byrow.pdf', device = "pdf", width= 10, height =5)

jitter_pos=position_jitter(width = .25, height = 0, seed = 1)
ggplot(data, aes(x=Var1, y=log10(expon_error), group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5, position= jitter_pos) + theme_classic() + xlab("simulated alpha amplitude") + ylab("log 10 arrhythmic slope error")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_hline(yintercept = 0, linetype= 'dashed')

ggsave('~/Desktop/alertness_2023/Figures/Simulated_amplitude_scatter_error_expon.pdf', device = "pdf", width= 10, height =5)


jitter_pos=position_jitter(width = .25, height = 0, seed = 1)
ggplot(data, aes(x=Var1, y=mse_BIC, group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5, position= jitter_pos) + theme_classic() + xlab("simulated alpha amplitude") + ylab("residual variance (a.u.)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') 


ggplot(data, aes(x=Var1, y=expon_BIC, group=Var1, fill = 'Var1', colour = 'Var1'))+  ggdist::stat_halfeye(adjust = .5, width = .5, .width = 0, justification = -.5, alpha=0.5, point_alpha= 0) + geom_boxplot(width = .25, outlier.shape = NA, colour= '#202020', position = position_dodge(1)) + theme_classic() + xlab("simulated alpha amplitude") + ylab("estimated arrhythmic slope")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_hline(yintercept = 1, linetype= 'dashed') + coord_cartesian(ylim = c(0.7, 1.3)) + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_color_manual(values=c('#10A0C0', '#D97D08'))

ggsave('~/Desktop/alertness_2023/Figures/Simulated_amplitude_boxplot_plot.pdf', device = "pdf", width= 10, height =5)


ggplot(data, aes(x=Var1, y=mse_BIC, group=Var1, fill = 'Var1', colour = 'Var1'))+  ggdist::stat_halfeye(adjust = .5, width = .5, .width = 0, justification = -.5, alpha=0.5, point_alpha= 0) + geom_boxplot(width = .25, outlier.shape = NA, colour= '#202020', position = position_dodge(1)) + theme_classic() + ylab("residual variance (a.u.)") + xlab("simulated alpha amplitude")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')  + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_color_manual(values=c('#10A0C0', '#D97D08'))

ggsave('~/Desktop/alertness_2023/Figures/Simulated_amplitude_boxplot_MSE.pdf', device = "pdf", width= 10, height =5)

ggplot(data, aes(x=Var1, y=corrspec_error, group=Var1, fill = 'Var1', colour = 'Var1'))+  ggdist::stat_halfeye(adjust = .5, width = .5, .width = 0, justification = -.5, alpha=0.5, point_alpha= 0) + geom_boxplot(width = .25, outlier.shape = NA, colour= '#202020', position = position_dodge(1)) + theme_classic() + ylab("residual rhythmic variance (a.u.)") + xlab("simulated alpha amplitude")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')  + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_color_manual(values=c('#10A0C0', '#D97D08')) + coord_cartesian(ylim = c(0,0.075))

ggsave('~/Desktop/alertness_2023/Figures/Simulated_amplitude_boxplot_residual_var_peaks.pdf', device = "pdf", width= 10, height =5)


# corr plot between corr spec and the exponent 
# tt(22:36)

data= read.csv('~/Documents/McGill/simulations4Giu/Simulations_amplitudes_output.csv', header = TRUE)
data$corralpha=rowMeans(corrspec[,22:36])
data$corralphalinear=rowMeans(corrspecLinear[,22:36])
data$alpha_amplitude= data$Var1-0.3
data$expon_error= (data$expon_BIC-1)^2
data$corrspec_error= rowMeans(corrspec_error)

# add in column for beta even though we do not simulate changes 
data$corrbeta=rowMeans(corrspec[,37:73])
data$corrbetalinear=rowMeans(corrspecLinear[,37:73])

peak_params_cf= read.csv('~/Documents/McGill/simulations4Giu/Simulations_amplitude_peaks_centerFreq.csv', header = FALSE)
peak_params_amp= read.csv('~/Documents/McGill/simulations4Giu/Simulations_amplitude_peaks_amplitude.csv', header = FALSE)

peak_params_cf= as.matrix(peak_params_cf)
peak_params_amp= as.matrix(peak_params_amp)

peak_params_amp[which(peak_params_cf <8 | peak_params_cf >12)] = NaN
peak_params_cf[which(peak_params_cf <8 | peak_params_cf >12)] = NaN

data$corralphamodel=apply(peak_params_amp, 1,max,na.rm = TRUE)
data$corralphamodel[data$corralphamodel== -Inf] =NaN

peak_params_cf= read.csv('~/Documents/McGill/simulations4Giu/Simulations_amplitude_peaks_centerFreq.csv', header = FALSE)
peak_params_amp= read.csv('~/Documents/McGill/simulations4Giu/Simulations_amplitude_peaks_amplitude.csv', header = FALSE)

peak_params_cf= as.matrix(peak_params_cf)
peak_params_amp= as.matrix(peak_params_amp)

peak_params_amp[which(peak_params_cf <14 | peak_params_cf >30)] = NaN
peak_params_cf[which(peak_params_cf <14 | peak_params_cf >30)] = NaN

data$corrbetamodel=apply(peak_params_amp, 1,max,na.rm = TRUE)
data$corrbetamodel[data$corrbetamodel== -Inf] =NaN

data$corralphamodel_error= (data$corralphamodel-0.7)^2
data$expon_error= (data$expon_BIC-1)

ggplot(data, aes(x=log10(corrspec_error), y=expon_error))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in rhythmic component") + ylab("error in arrhythmic slope")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_hline(yintercept = 0, linetype= 'dashed') + stat_smooth(data= data[data$expon_error >0,], aes(x=log10(corrspec_error), y=expon_error), method = "glm",formula = y ~ poly(x, 1),fullrange = FALSE, color= 'black', linetype='dashed', se = FALSE)+ stat_smooth(data= data[data$expon_error <0,], aes(x=log10(corrspec_error), y=expon_error) , method = "glm",formula = y ~ poly(x, 1),fullrange = FALSE, color= 'black', linetype='dashed', se= FALSE)

ggsave('~/Desktop/alertness_2023/Figures/Simulated_amplitude_scatter_plot_two_types_of_error.pdf', device = "pdf", width= 5, height =5)

ggplot(data, aes(x=log10(corralphamodel_error), y=expon_error, group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in rhythmic component") + ylab("error in arrhythmic slope")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_hline(yintercept = 0, linetype= 'dashed') + facet_wrap(~Var1, ncol = 5)

ggsave('~/Desktop/alertness_2023/Figures/Simulated_amplitude_scatter_plot_two_types_of_error_fromModelledAmplitudes_byrow.pdf', device = "pdf", width= 10, height =5)


DescTools::SpearmanRho(data$corralpha, data$corralphalinear, use = c("complete.obs"), conf.level = 0.95) # 0.9783963

# remove bad estimates 
data2= data[abs(data$mse_BIC) < 3*sd(data$mse_BIC) + mean(data$mse_BIC) ,]
corrspec2= corrspec[abs(data$mse_BIC) < 3*sd(data$mse_BIC) + mean(data$mse_BIC)   ,]
corrspec2= corrspec2[data2$expon_BIC > 0.5 & data2$expon_BIC < 1.5  ,]
data2= data2[data2$expon_BIC > 0.5 & data2$expon_BIC < 1.5 ,]

DescTools::SpearmanRho(data2$expon_BIC, rowMeans(corrspec2[,22:36]), use = c("complete.obs"), conf.level = 0.95) # -0.007786458
DescTools::SpearmanRho(data2$expon_BIC, data2$corralphamodel, use = c("complete.obs"), conf.level = 0.95) # 0.06696761
DescTools::SpearmanRho(data2$expon_BIC, data2$corralphalinear, use = c("complete.obs"), conf.level = 0.95) #0.06101575

DescTools::SpearmanRho(rowMeans(corrspec2[,22:36]), data2$corralphamodel, use = c("complete.obs"), conf.level = 0.95) # 0.9570765

spr1=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.3], rowMeans(corrspec2[data2$Var1==0.3,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr2=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.5], rowMeans(corrspec2[data2$Var1==0.5,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.7], rowMeans(corrspec2[data2$Var1==0.7,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.9], rowMeans(corrspec2[data2$Var1==0.9,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.0], rowMeans(corrspec2[data2$Var1==1.0,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.2], rowMeans(corrspec2[data2$Var1==1.2,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.4], rowMeans(corrspec2[data2$Var1==1.4,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.6], rowMeans(corrspec2[data2$Var1==1.6,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.8], rowMeans(corrspec2[data2$Var1==1.8,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr10=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==2.0], rowMeans(corrspec2[data2$Var1==2.0,22:36]), use = c("complete.obs"), conf.level = 0.95) 


data4plot=data.frame(freqs= c(0.3,0.5,0.7,0.9,1.0,1.2,1.4,1.6,1.8,2.0),
                     corrs=c(spr1[[1]], spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]], spr10[[1]]), 
                     lower=c(spr1[[2]], spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]], spr10[[2]]), 
                     upper=c(spr1[[3]], spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]], spr10[[3]]))


ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill='1')) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated rhythmic alpha amplitude (a.u.)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_alpha_slope_by_simulated_amplitude.pdf', device = "pdf", height = 5, width = 5)


lm00=lm(expon_BIC ~ corralpha*alpha_amplitude, data2)
summary(lm00)
sjPlot::tab_model(lm00)

lm00=lm(expon_BIC ~ poly(alpha_amplitude,2)*corralpha, data2)
summary(lm00)

data4plot2= data4plot

spr1=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.3], data2$corralphamodel[data2$Var1==0.3], use = c("complete.obs"), conf.level = 0.95) 
spr2=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.5], data2$corralphamodel[data2$Var1==0.5], use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.7], data2$corralphamodel[data2$Var1==0.7], use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.9], data2$corralphamodel[data2$Var1==0.9], use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.0], data2$corralphamodel[data2$Var1==1.0], use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.2], data2$corralphamodel[data2$Var1==1.2], use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.4], data2$corralphamodel[data2$Var1==1.4], use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.6], data2$corralphamodel[data2$Var1==1.6], use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.8], data2$corralphamodel[data2$Var1==1.8], use = c("complete.obs"), conf.level = 0.95) 
spr10=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==2.0], data2$corralphamodel[data2$Var1==2.0], use = c("complete.obs"), conf.level = 0.95) 


data4plot=data.frame(freqs= c(0.3,0.5,0.7,0.9,1.0,1.2,1.4,1.6,1.8,2.0),
                     corrs=c(spr1[[1]], spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]], spr10[[1]]), 
                     lower=c(spr1[[2]], spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]], spr10[[2]]), 
                     upper=c(spr1[[3]], spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]], spr10[[3]]),
                     nototals=c(sum(is.na(data2$corrbetamodel[data2$Var1==0.3]))/length(data2$corrbetamodel[data2$Var1==0.3]),
                                 sum(is.na(data2$corralphamodel[data2$Var1==0.5]))/length(data2$corralphamodel[data2$Var1==0.5]),                          sum(is.na(data2$corralphamodel[data2$Var1==0.7]))/length(data2$corralphamodel[data2$Var1==0.7]),sum(is.na(data2$corralphamodel[data2$Var1==0.9]))/length(data2$corralphamodel[data2$Var1==0.9]), sum(is.na(data2$corralphamodel[data2$Var1==1.0]))/length(data2$corralphamodel[data2$Var1==1.0]), sum(is.na(data2$corralphamodel[data2$Var1==1.2]))/length(data2$corralphamodel[data2$Var1==1.2]), sum(is.na(data2$corralphamodel[data2$Var1==1.4]))/length(data2$corralphamodel[data2$Var1==1.4]), sum(is.na(data2$corralphamodel[data2$Var1==1.6]))/length(data2$corralphamodel[data2$Var1==1.6]),                  sum(is.na(data2$corralphamodel[data2$Var1==1.8]))/length(data2$corralphamodel[data2$Var1==1.8]), sum(is.na(data2$corralphamodel[data2$Var1==2.0]))/length(data2$corralphamodel[data2$Var1==2.0])))


data4plot$nototals= data4plot$nototals+0.000001
ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= -1*log10(100*nototals), fill= -1*log10(100*nototals))) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2()   + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14)) + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white")+ geom_point( size=5)
               
ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_alpha_slope_by_simulated_amplitude_modeled_params.pdf', device = "pdf", height = 5, width = 8)


data4plot2$nototals =0
data4plot=rbind(data4plot2, data4plot)
data4plot$type= rep(c('subtraction', 'model'), each =10)

data4plot4 = data4plot

data4plot$nototals= data4plot$nototals+0.000001
ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= -1*log10(100*nototals), fill= -1*log10(100*nototals))) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2()   + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14)) + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white")+ geom_point( size=5) + facet_wrap(~type) + geom_hline(yintercept = c(-0.15, 0.15), linetype= 'dashed')

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_alpha_slope_by_simulated_amplitude_comparison_alpha_method.pdf', device = "pdf", height = 5, width = 12)



spr1=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.3], data2$corralphalinear[data2$Var1==0.3], use = c("complete.obs"), conf.level = 0.95) 
spr2=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.5], data2$corralphalinear[data2$Var1==0.5], use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.7], data2$corralphalinear[data2$Var1==0.7], use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.9], data2$corralphalinear[data2$Var1==0.9], use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.0], data2$corralphalinear[data2$Var1==1.0], use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.2], data2$corralphalinear[data2$Var1==1.2], use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.4], data2$corralphalinear[data2$Var1==1.4], use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.6], data2$corralphalinear[data2$Var1==1.6], use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.8], data2$corralphalinear[data2$Var1==1.8], use = c("complete.obs"), conf.level = 0.95) 
spr10=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==2.0], data2$corralphalinear[data2$Var1==2.0], use = c("complete.obs"), conf.level = 0.95) 


data4plot=data.frame(freqs= c(0.3,0.5,0.7,0.9,1.0,1.2,1.4,1.6,1.8,2.0),
                     corrs=c(spr1[[1]], spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]], spr10[[1]]), 
                     lower=c(spr1[[2]], spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]], spr10[[2]]), 
                     upper=c(spr1[[3]], spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]], spr10[[3]]))


ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill='1')) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated rhythmic alpha amplitude (a.u.)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')

ggsave('~/Desktop/alertness_2023/Figures/Simulations_amplitude_between_alpha_slope_by_simulated_linearspace.pdf', device = "pdf", height = 5, width = 5)





data4plot$nototals =0
data4plot$type = 'linear'
data4plot=rbind(data4plot4, data4plot)
data4plot$type = factor(data4plot$type, levels = c('model', 'subtraction', 'linear'))

ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill= '1')) +
    ggpubr::theme_classic2()   + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white")+ geom_point( size=5) + facet_wrap(~type) + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + geom_hline(yintercept = c(-0.15, 0.15), linetype= 'dashed')

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_alpha_slope_by_simulated_amplitude_model_no_NAs_compare_all.pdf', device = "pdf", height = 5, width = 15)




# look at relationship with beta 

spr1=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.3], rowMeans(corrspec2[data2$Var1==0.3,37:73]), use = c("complete.obs"), conf.level = 0.95) 
spr2=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.5], rowMeans(corrspec2[data2$Var1==0.5,37:73]), use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.7], rowMeans(corrspec2[data2$Var1==0.7,37:73]), use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.9], rowMeans(corrspec2[data2$Var1==0.9,37:73]), use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1], rowMeans(corrspec2[data2$Var1==1,37:73]), use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.2], rowMeans(corrspec2[data2$Var1==1.2,37:73]), use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.4], rowMeans(corrspec2[data2$Var1==1.4,37:73]), use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.6], rowMeans(corrspec2[data2$Var1==1.6,37:73]), use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.8], rowMeans(corrspec2[data2$Var1==1.8,37:73]), use = c("complete.obs"), conf.level = 0.95) 
spr10=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==2.0], rowMeans(corrspec2[data2$Var1==2.0,37:73]), use = c("complete.obs"), conf.level = 0.95) 


data4plot=data.frame(freqs= c(0.3,0.5,0.7,0.9,1.0,1.2,1.4,1.6,1.8,2.0),
                     corrs=c(spr1[[1]], spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]], spr10[[1]]), 
                     lower=c(spr1[[2]], spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]], spr10[[2]]), 
                     upper=c(spr1[[3]], spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]], spr10[[3]]))

data4plot2=data4plot

ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill='1')) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship w/ beta power (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_beta_slope_by_simulated_amplitude.pdf', device = "pdf", height = 5, width = 5)


spr1=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.3], data2$corrbetamodel[data2$Var1==0.3], use = c("complete.obs"), conf.level = 0.95) 
spr2=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.5], data2$corrbetamodel[data2$Var1==0.5], use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.7], data2$corrbetamodel[data2$Var1==0.7], use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.9], data2$corrbetamodel[data2$Var1==0.9], use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1], data2$corrbetamodel[data2$Var1==1], use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.2], data2$corrbetamodel[data2$Var1==1.2], use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.4], data2$corrbetamodel[data2$Var1==1.4], use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.6], data2$corrbetamodel[data2$Var1==1.6], use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.8], data2$corrbetamodel[data2$Var1==1.8], use = c("complete.obs"), conf.level = 0.95) 
spr10=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==2.0], data2$corrbetamodel[data2$Var1==2.0], use = c("complete.obs"), conf.level = 0.95) 


data4plot=data.frame(freqs= c(0.3,0.5,0.7,0.9,1.0,1.2,1.4,1.6,1.8,2.0),
                     corrs=c(spr1[[1]], spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]], spr10[[1]]), 
                     lower=c(spr1[[2]], spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]], spr10[[2]]), 
                     upper=c(spr1[[3]], spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]], spr10[[3]]),
                     nototals=c(sum(is.na(data2$corrbetamodel[data2$Var1==0.3]))/length(data2$corrbetamodel[data2$Var1==0.3]),
                                 sum(is.na(data2$corralphamodel[data2$Var1==0.5]))/length(data2$corralphamodel[data2$Var1==0.5]),                          sum(is.na(data2$corralphamodel[data2$Var1==0.7]))/length(data2$corralphamodel[data2$Var1==0.7]),sum(is.na(data2$corralphamodel[data2$Var1==0.9]))/length(data2$corralphamodel[data2$Var1==0.9]), sum(is.na(data2$corralphamodel[data2$Var1==1.0]))/length(data2$corralphamodel[data2$Var1==1.0]), sum(is.na(data2$corralphamodel[data2$Var1==1.2]))/length(data2$corralphamodel[data2$Var1==1.2]), sum(is.na(data2$corralphamodel[data2$Var1==1.4]))/length(data2$corralphamodel[data2$Var1==1.4]), sum(is.na(data2$corralphamodel[data2$Var1==1.6]))/length(data2$corralphamodel[data2$Var1==1.6]),                  sum(is.na(data2$corralphamodel[data2$Var1==1.8]))/length(data2$corralphamodel[data2$Var1==1.8]), sum(is.na(data2$corralphamodel[data2$Var1==2.0]))/length(data2$corralphamodel[data2$Var1==2.0])))

data4plot3=data4plot[,1:4]

data4plot$nototals= data4plot$nototals+0.000001
ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= -1*log10(100*nototals), fill= -1*log10(100*nototals))) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2()   + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14)) + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r) w/ beta power") + geom_errorbar(width=0)+geom_point(size=6, colour= "white")+ geom_point( size=5)

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_beta_slope_by_simulated_amplitude_modeled_params.pdf', device = "pdf", height = 5, width = 8)



spr1=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.3], data2$corrbetalinear[data2$Var1==0.3], use = c("complete.obs"), conf.level = 0.95) 
spr2=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.5], data2$corrbetalinear[data2$Var1==0.5], use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.7], data2$corrbetalinear[data2$Var1==0.7], use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.9], data2$corrbetalinear[data2$Var1==0.9], use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1], data2$corrbetalinear[data2$Var1==1], use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.2], data2$corrbetalinear[data2$Var1==1.2], use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.4], data2$corrbetalinear[data2$Var1==1.4], use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.6], data2$corrbetalinear[data2$Var1==1.6], use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.8], data2$corrbetalinear[data2$Var1==1.8], use = c("complete.obs"), conf.level = 0.95) 
spr10=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==2.0], data2$corrbetalinear[data2$Var1==2.0], use = c("complete.obs"), conf.level = 0.95) 


data4plot=data.frame(freqs= c(0.3,0.5,0.7,0.9,1.0,1.2,1.4,1.6,1.8,2.0),
                     corrs=c(spr1[[1]], spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]], spr10[[1]]), 
                     lower=c(spr1[[2]], spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]], spr10[[2]]), 
                     upper=c(spr1[[3]], spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]], spr10[[3]]))


ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill='1')) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated rhythmic alpha frequenyc (Hz)") + ylab("estimated relationship w/ beta (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')

data4plot4=data4plot

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_beta_slope_by_simulated_linearspace_amplitude.pdf', device = "pdf", height = 5, width = 5)




data4plot=rbind(data4plot3, data4plot2, data4plot4)
data4plot$type =  rep(c('model', 'subtraction', 'linear'), each=10)
data4plot$type = factor(data4plot$type, levels = c('model', 'subtraction', 'linear'))

ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill= '1')) +
    ggpubr::theme_classic2()   + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white")+ geom_point( size=5) + facet_wrap(~type) + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + geom_hline(yintercept = c(-0.15, 0.15), linetype= 'dashed')

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_beta_slope_by_simulated_amplitude_model_no_NAs_compare_all.pdf', device = "pdf", height = 5, width = 15)




```


```{r plot example fitted spectrums }

cbbPalette= c("#4f89e0", "#f5ec6c",'#156605',"#76D7C4","#268236", '#4d3d87','#593d80', '#3b49e3')


# read data and compute data for demographic table
data=read.csv('/Users/jason/Documents/McGill/simulations4Giu/Simulations_exponent_PSD.csv', header = FALSE)
aperiodic_fit=read.csv('/Users/jason/Documents/McGill/simulations4Giu/Simulations_exponent_fitted_aperiodicspectrum.csv', header = FALSE)
periodic_fit=read.csv('/Users/jason/Documents/McGill/simulations4Giu/Simulations_exponent_fitted_periodicspectrum.csv', header = FALSE)
fpsd=read.csv('/Users/jason/Documents/McGill/simulations4Giu/Simulations_exponent_fitted_spectrum.csv', header = FALSE)

peak_cf_BIC= read.csv('~/Documents/McGill/simulations4Giu/Simulations_exponent_peaks_centerFreq.csv', header = FALSE)
peak_amp_BIC= read.csv('~/Documents/McGill/simulations4Giu/Simulations_exponent_peaks_amplitude.csv', header = FALSE)
peak_std_BIC= read.csv('~/Documents/McGill/simulations4Giu/Simulations_exponent_peaks_std.csv', header = FALSE)

roi_index= 1111

PSD= data[roi_index,]
aperiodic= log10(aperiodic_fit[roi_index,])
periodic= log10(periodic_fit[roi_index,])
fooof= log10(fpsd[roi_index,])
corrspec= PSD-aperiodic

target_LSP= rbind( stack(corrspec))
target_LSP$Group = rep(c('periodic'), each=148)

target_LSP$ind = plyr::mapvalues(target_LSP$ind , unique(target_LSP$ind ), seq(1,50,1/3))
target_LSP$ind= as.numeric(as.character(target_LSP$ind))

ggplot(target_LSP, aes(x= ind, y = values, fill= Group, colour= Group)) +  geom_line() + ggpubr::theme_classic2() +  coord_cartesian(xlim = c(1, 50), ylim= c(-0.4, 0.8)) + geom_hline(yintercept = 0, linetype = 'dashed')

ggsave('~/Documents/FOOOF_BICvsVANILLA/figures/SIMULATIONS_example_PERIODIC_No_1111.pdf', device = "pdf", width=6, height=5, dpi=800)

# plot another example 

peak_cf_BIC[1111, ]
peak_amp_BIC[1111, ]
peak_std_BIC[1111, ]

G0= 0.6013375*exp((-1*((seq(1,50,1/3) - 9.568346)^2))/(2*(2.075968^2)))
G2= 0.4085625*exp((-1*((seq(1,50,1/3) - 18.40977)^2))/(2*(3.346625^2)))

G1= G0 + G2

target_LSP= rbind( stack(PSD), stack(aperiodic), stack(fooof))
target_LSP$Group = rep(c('PSD', 'aperiodic', 'specparam'), each=148)

target_LSP$ind = plyr::mapvalues(target_LSP$ind , unique(target_LSP$ind ), seq(1,50,1/3))
target_LSP$ind= as.numeric(as.character(target_LSP$ind))

ggplot(target_LSP, aes(x= ind, y = values, fill= Group, colour= Group)) + geom_ribbon(data= target_LSP, aes(ymin = rep(unlist(array(aperiodic[1,])),3), ymax = rep(unlist(array(aperiodic[1,]))+G0,3)), color = 'white',fill = "blue", alpha = .25)  + geom_ribbon(data= target_LSP, aes(ymin = rep(unlist(array(aperiodic[1,])),3), ymax = rep(unlist(array(aperiodic[1,]))+G2,3)), color = 'white',fill = "blue", alpha = .25) + geom_line() + ggpubr::theme_classic2() +  coord_cartesian(xlim = c(1, 50)) 

ggsave('~/Documents/FOOOF_BICvsVANILLA/figures/SIMULATIONS_example_Spectrum_No_1111.pdf', device = "pdf", width=6, height=5, dpi=800)



# bad example 


roi_index= 888

PSD= data[roi_index,]
aperiodic= log10(aperiodic_fit[roi_index,])
periodic= log10(periodic_fit[roi_index,])
fooof= log10(fpsd[roi_index,])
corrspec= PSD-aperiodic

target_LSP= rbind( stack(corrspec))
target_LSP$Group = rep(c('periodic'), each=148)

target_LSP$ind = plyr::mapvalues(target_LSP$ind , unique(target_LSP$ind ), seq(1,50,1/3))
target_LSP$ind= as.numeric(as.character(target_LSP$ind))

ggplot(target_LSP, aes(x= ind, y = values, fill= Group, colour= Group)) +  geom_line() + ggpubr::theme_classic2() +  coord_cartesian(xlim = c(1, 50), ylim= c(-0.4, 0.8)) + geom_hline(yintercept = 0, linetype = 'dashed')

ggsave('~/Documents/FOOOF_BICvsVANILLA/figures/SIMULATIONS_example_PERIODIC_No_888.pdf', device = "pdf", width=6, height=5, dpi=800)

# plot another example 

peak_cf_BIC[888, ]
peak_amp_BIC[888, ]
peak_std_BIC[888, ]

G0= 0.494104*exp((-1*((seq(1,50,1/3) - 12.57732)^2))/(2*(7.65586^2)))

target_LSP= rbind( stack(PSD), stack(aperiodic), stack(fooof))
target_LSP$Group = rep(c('PSD', 'aperiodic', 'specparam'), each=148)

target_LSP$ind = plyr::mapvalues(target_LSP$ind , unique(target_LSP$ind ), seq(1,50,1/3))
target_LSP$ind= as.numeric(as.character(target_LSP$ind))

ggplot(target_LSP, aes(x= ind, y = values, fill= Group, colour= Group)) + geom_ribbon(data= target_LSP, aes(ymin = rep(unlist(array(aperiodic[1,])),3), ymax = rep(unlist(array(aperiodic[1,]))+G0,3)), color = 'white',fill = "blue", alpha = .25)   + geom_line() + ggpubr::theme_classic2() +  coord_cartesian(xlim = c(1, 50)) 

ggsave('~/Documents/FOOOF_BICvsVANILLA/figures/SIMULATIONS_example_Spectrum_No_888.pdf', device = "pdf", width=6, height=5, dpi=800)




roi_index= 3818

PSD= data[roi_index,]
aperiodic= log10(aperiodic_fit[roi_index,])
periodic= log10(periodic_fit[roi_index,])
fooof= log10(fpsd[roi_index,])

target_LSP= rbind( stack(periodic))
target_LSP$Group = rep(c('periodic'), each=148)

target_LSP$ind = plyr::mapvalues(target_LSP$ind , unique(target_LSP$ind ), seq(1,50,1/3))
target_LSP$ind= as.numeric(as.character(target_LSP$ind))

ggplot(target_LSP, aes(x= ind, y = values, fill= Group, colour= Group)) +  geom_line() + ggpubr::theme_classic2() +  coord_cartesian(xlim = c(1, 50))

ggsave('~/Documents/FOOOF_BICvsVANILLA/figures/SIMULATIONS_example_PERIODIC_No_3818.pdf', device = "pdf", width=6, height=5, dpi=800)

# plot another example 

peak_cf_BIC[3818, ]
peak_amp_BIC[3818, ]
peak_std_BIC[3818, ]

G0= 0.5294917*exp((-1*((seq(1,50,1/3) - 11.55287)^2))/(2*(0.5453429^2)))
G1= 0.4292724*exp((-1*((seq(1,50,1/3) - 11.34478)^2))/(2*(12^2)))

target_LSP= rbind( stack(PSD), stack(aperiodic), stack(fooof))
target_LSP$Group = rep(c('PSD', 'aperiodic', 'specparam'), each=148)

target_LSP$ind = plyr::mapvalues(target_LSP$ind , unique(target_LSP$ind ), seq(1,50,1/3))
target_LSP$ind= as.numeric(as.character(target_LSP$ind))

ggplot(target_LSP, aes(x= ind, y = values, fill= Group, colour= Group)) + geom_ribbon(data= target_LSP, aes(ymin = rep(unlist(array(aperiodic[1,])),3), ymax = rep(unlist(array(aperiodic[1,]))+G1,3)), color = 'white',fill = "blue", alpha = .25)   +
  geom_ribbon(data= target_LSP, aes(ymin = rep(unlist(array(aperiodic[1,])),3), ymax = rep(unlist(array(aperiodic[1,]))+G1 + G0,3)), color = 'white',fill = "blue", alpha = .25) +  geom_line() + ggpubr::theme_classic2() +  coord_cartesian(xlim = c(1, 50)) 

ggsave('~/Documents/FOOOF_BICvsVANILLA/figures/SIMULATIONS_example_Spectrum_No_3818.pdf', device = "pdf", width=6, height=5, dpi=800)



```


```{r simulated exponents}

library(ggplot2)
library(dplyr)

data= read.csv('~/Documents/McGill/simulations4Giu/Simulations_exponent_output.csv', header = TRUE)

corrspec = read.csv('~/Documents/McGill/simulations4Giu/Exponent_Simulations_corrspec.csv', header = FALSE)

corrspeclinear = read.csv('~/Documents/McGill/simulations4Giu/Exponent_Simulations_corrspec_linear.csv', header = FALSE)

corrspec_error = read.csv('~/Documents/McGill/simulations4Giu/Exponent_Simulations_error_signed.csv', header = FALSE)
aperiodic_error = read.csv('~/Documents/McGill/simulations4Giu/Exponent_Simulations__aperiodic_error_signed.csv', header = FALSE)

offset_error = read.csv('~/Documents/McGill/simulations4Giu/Exponent_Simulations__offset_error_signed.csv', header = FALSE)

cor.test(data$expon_BIC, data$Var1) # 0.9084615 
cor.test(data$mse_BIC, data$Var1) # -3.333008e-05 

data$expon_error=data$Var1-data$expon_BIC

data$corrspec_error= rowMeans(corrspec_error)
data$aperiodic_error= rowMeans(aperiodic_error)
data$offset_error= offset_error$V1
cor.test(data$corrspec_error, data$Var1) # -0.006023982
cor.test(data$corrspec_error, data$aperiodic_error, method = 'spearman')
cor.test(data$corrspec_error, data$offset_error, method = 'spearman')

#data$Var1 = factor(data$Var1)

data$corralpha= rowMeans(corrspec[,22:36])
data$corralphaerror= rowMeans(corrspec_error[,22:36])
data$corralphalinear=rowMeans(corrspeclinear[,22:36])

data$expon_error=data$Var1-data$expon_BIC
cor.test(data$expon_error, data$offset_error, method = 'spearman')



jitter_pos=position_jitter(width = .25, height = 0, seed = 1)
ggplot(data, aes(x=Var1, y=log10(corrspec_error), group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5, position= jitter_pos) + theme_classic() + xlab("simulated arrhythmic slope") + ylab("log 10 error in rhythmic component")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') 

ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_scatter_plot_error.pdf', device = "pdf", width= 10, height =5)


ggplot(data, aes(x=aperiodic_error, y=corralpha, group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in rhythmic component") + ylab("error in arrhythmic slope")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') 

#ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_scatter_plot_two_types_of_error.pdf', device = "pdf", width= 5, height =5)

ggplot(data, aes(x=offset_error, y=corrspec_error, group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in rhythmic component") + ylab("error in arrhythmic slope")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = 0.0, linetype= 'dashed') 

#ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_scatter_plot_two_types_of_error_byrow.pdf', device = "pdf", width= 10, height =5)

ggplot(data, aes(x=Var1, y=mse_BIC, group=Var1, fill = 'Var1', colour = 'Var1'))+  ggdist::stat_halfeye(adjust = .5, width = .5, .width = 0, justification = -.5, alpha=0.5, point_alpha= 0) + geom_boxplot(width = .25, outlier.shape = NA, colour= '#202020', position = position_dodge(1)) + theme_classic() + xlab("simulated exponent") + ylab("residual variance (a.u.)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')  + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_color_manual(values=c('#10A0C0', '#D97D08'))

ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_boxplot_MSE.pdf', device = "pdf", width= 10, height =5)


ggplot(data, aes(x=Var1, y=corralpha, group=Var1, fill = 'Var1', colour = 'Var1'))+  ggdist::stat_halfeye(adjust = .5, width = .5, .width = 0, justification = -.5, alpha=0.5, point_alpha= 0) + geom_boxplot(width = .25, outlier.shape = NA, colour= '#202020', position = position_dodge(1)) + theme_classic() + xlab("simulated exponent") + ylab("rythmic alpha (a.u.)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')  + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_color_manual(values=c('#10A0C0', '#D97D08')) + geom_hline(yintercept = 0.6457, linetype= 'dashed') + coord_cartesian(ylim = c(0,1))

ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_corralpha_power.pdf', device = "pdf", width= 10, height =5)


peak_params_cf= read.csv('~/Documents/McGill/simulations4Giu/Simulations_exponent_peaks_centerFreq.csv', header = FALSE)
peak_params_amp= read.csv('~/Documents/McGill/simulations4Giu/Simulations_exponent_peaks_amplitude.csv', header = FALSE)

peak_params_cf= as.matrix(peak_params_cf)
peak_params_amp= as.matrix(peak_params_amp)

peak_params_amp[which(peak_params_cf <8 | peak_params_cf >12)] = NaN
peak_params_cf[which(peak_params_cf <8 | peak_params_cf >12)] = NaN

data$corralphamodel=apply(peak_params_amp, 1, max, na.rm = TRUE)
data$corralphamodel[data$corralphamodel == -Inf] = NaN

ggplot(data, aes(x=Var1, y=corralphamodel, group=Var1, fill = 'Var1', colour = 'Var1'))+  ggdist::stat_halfeye(adjust = .5, width = .5, .width = 0, justification = -.5, alpha=0.5, point_alpha= 0) + geom_boxplot(width = .25, outlier.shape = NA, colour= '#202020', position = position_dodge(1)) + theme_classic() + xlab("simulated exponent") + ylab("rythmic alpha amplitude")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')  + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_color_manual(values=c('#10A0C0', '#D97D08')) + geom_hline(yintercept = 0.7, linetype= 'dashed') + coord_cartesian(ylim = c(0.25,0.9))

ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_peak_alpha_power.pdf', device = "pdf", width= 10, height =5)


ggplot(data, aes(x=expon_error, y=corralphamodel, group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("error in exponent") + ylab("corrected alpha power (log-log)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = 0, linetype= 'dashed') + geom_hline(yintercept = 0.7, linetype= 'dashed')

ggplot(data[abs(scale(data$mse_BIC)[,1]) < 2.5,], aes(x=expon_error, y=corralpha, group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("error in exponent") + ylab("corrected alpha power (log-log)")  + coord_cartesian(ylim = c(0.0, 1.5), xlim = c(-1.0, 0.6))+ theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = 0, linetype= 'dashed') + geom_hline(yintercept = 0.7, linetype= 'dashed') + facet_wrap(~Var1, nrow = 5, scales = "free") + smplot2::sm_statCorr(corr_method = 'spearman')

ggplot(data, aes(x=expon_BIC, y=corralpha, group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("error in exponent") + ylab("corrected alpha power (log-log)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = 0, linetype= 'dashed') + geom_hline(yintercept = 0.0, linetype= 'dashed')

ggplot(data, aes(x=expon_error, y=log10(corralphalinear), group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("error in exponent") + ylab("corrected alpha power (log-log)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = 0, linetype= 'dashed') 

data$overestimated = data$expon_error >0 

ggplot(data, aes(x=overestimated, y=corralpha, group=overestimated, fill = 'Var1', colour = 'Var1'))+  ggdist::stat_halfeye(adjust = .5, width = .5, .width = 0, justification = -.5, alpha=0.5, point_alpha= 0) + geom_boxplot(width = .25, outlier.shape = NA, colour= '#202020', position = position_dodge(1)) + theme_classic() + xlab("simulated exponent") + ylab("residual variance (a.u.)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')  + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_color_manual(values=c('#10A0C0', '#D97D08'))


RVAideMemoire::perm.t.test(data$corralpha[data$overestimated],data$corralpha[!data$overestimated], nperm=1000, paired=FALSE)


# corr plot between corr spec and the exponent 
# tt(22:36)

data= read.csv('~/Documents/McGill/simulations4Giu/Simulations_exponent_output.csv', header = TRUE)
data$corralpha=rowMeans(corrspec[,22:36])
data$corralphalinear=rowMeans(corrspeclinear[,22:36])
data$alpha_amplitude= data$Var1-0.6

# add in column for beta even though we do not simulate changes 
data$corrbeta=rowMeans(corrspec[,37:73])
data$corrbetalinear=rowMeans(corrspeclinear[,37:73])
data$corrthetalinear=rowMeans(corrspeclinear[,10:21])
data$corrspec_error= rowMeans(corrspec_error)
data$aperiodic_error= rowMeans(aperiodic_error)
data$offset_error= offset_error$V1


peak_params_cf= read.csv('~/Documents/McGill/simulations4Giu/Simulations_exponent_peaks_centerFreq.csv', header = FALSE)
peak_params_amp= read.csv('~/Documents/McGill/simulations4Giu/Simulations_exponent_peaks_amplitude.csv', header = FALSE)

peak_params_cf= as.matrix(peak_params_cf)
peak_params_amp= as.matrix(peak_params_amp)

peak_params_amp[which(peak_params_cf <8 | peak_params_cf >12)] = NaN
peak_params_cf[which(peak_params_cf <8 | peak_params_cf >12)] = NaN

data$corralphamodel=apply(peak_params_amp, 1, max, na.rm = TRUE)
data$corralphamodel[data$corralphamodel == -Inf] = NaN

peak_params_cf= read.csv('~/Documents/McGill/simulations4Giu/Simulations_exponent_peaks_centerFreq.csv', header = FALSE)
peak_params_amp= read.csv('~/Documents/McGill/simulations4Giu/Simulations_exponent_peaks_amplitude.csv', header = FALSE)

peak_params_cf= as.matrix(peak_params_cf)
peak_params_amp= as.matrix(peak_params_amp)

peak_params_amp[which(peak_params_cf <12 | peak_params_cf >24)] = NaN
peak_params_cf[which(peak_params_cf <12 | peak_params_cf >24)] = NaN

data$corrbetamodel=apply(peak_params_amp, 1,max,na.rm = TRUE)
data$corrbetamodel[data$corrbetamodel== -Inf] =NaN

data$corralphamodel_error= (data$corralphamodel-0.7)^2
data$expon_error=data$Var1-data$expon_BIC

ggplot(data, aes(x=log10(corrspec_error), y=expon_error))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in rhythmic component") + ylab("error in arrhythmic slope")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_hline(yintercept = 0, linetype= 'dashed') + stat_smooth(data= data[data$expon_error >0,], aes(x=log10(corrspec_error), y=expon_error), method = "glm",formula = y ~ poly(x, 1),fullrange = FALSE, color= 'black', linetype='dashed', se = FALSE)+ stat_smooth(data= data[data$expon_error <0,], aes(x=log10(corrspec_error), y=expon_error) , method = "glm",formula = y ~ poly(x, 1),fullrange = FALSE, color= 'black', linetype='dashed', se= FALSE)

ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_scatter_plot_two_types_of_error_fromModelledAmplitudes.pdf', device = "pdf", width= 5, height =5)


ggplot(data, aes(x=log10(corralphamodel_error), y=expon_error, group=Var1))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in rhythmic component") + ylab("error in arrhythmic slope")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_hline(yintercept = 0, linetype= 'dashed') + facet_wrap(~Var1, ncol = 5)

ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_scatter_plot_two_types_of_error_fromModelledAmplitudes_byrow.pdf', device = "pdf", width= 10, height =5)

# remove bad estimates 
data2= data[abs(data$mse_BIC) < 3*sd(data$mse_BIC) + mean(data$mse_BIC) ,]
corrspec2= corrspec[abs(data$mse_BIC) < 3*sd(data$mse_BIC) + mean(data$mse_BIC)   ,]
corrspec2= corrspec2[data2$expon_BIC > 0.3 & data2$expon_BIC < 2.0  ,]
data2= data2[data2$expon_BIC > 0.3 & data2$expon_BIC < 2.0 ,]


DescTools::SpearmanRho(data2$corrspec_error, data2$offset_error, use = c("complete.obs"), conf.level = 0.95) # 0.2642543 0.2381087 0.2900173 

DescTools::SpearmanRho(data2$expon_error, data2$offset_error, use = c("complete.obs"), conf.level = 0.95) # 0.3302380 0.3051484 0.3548695 

DescTools::SpearmanRho(log10(data2$corralpha), data2$offset_error, use = c("complete.obs"), conf.level = 0.95) # 0.2137484 0.1869621 0.2402170 

data2$expon_error_sqd= data2$expon_error^2
data4reg= data.frame(scale(data2))
lm0=lm(corralpha ~ offset_error +expon_error + expon_error_sqd, data4reg)
sjPlot::tab_model(lm0)

lm0=lm(corralpha ~ offset_error, data4reg)
sjPlot::tab_model(lm0)

lm0=lm(corralpha ~ expon_error + expon_error_sqd, data4reg)
sjPlot::tab_model(lm0)

lm0=lm(corralphamodel ~ offset_error +expon_error + expon_error_sqd, data4reg)
sjPlot::tab_model(lm0)

ggplot(data2, aes(x=offset_error, y=corralpha))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("error in offset") + ylab("corrected alpha power (log-log)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = log10(0), linetype= 'dashed') + geom_hline(yintercept = 0.7, linetype= 'dashed') + geom_vline(xintercept = 0.0, linetype= 'dashed') + stat_smooth(method = "lm", formula = y ~ poly(x, 1), se = TRUE,fullrange = FALSE, color= 'black') 

ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_offset_error_power_relationship.pdf', device = "pdf", width= 5, height =5)

# make boxplot 

ggplot(data2, aes(x=expon_error, y=corralpha))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("error in offset") + ylab("corrected alpha power (log-log)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = log10(0), linetype= 'dashed') + geom_hline(yintercept = 0.7, linetype= 'dashed') + geom_vline(xintercept = 0.0, linetype= 'dashed') + stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = TRUE,fullrange = FALSE, color= 'black') 

ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_expon_error_power_relationship.pdf', device = "pdf", width= 5, height =5)



ggplot(data2, aes(x=offset_error, y=corralphamodel))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("error in offset") + ylab("modelled alpha power")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = log10(0), linetype= 'dashed') + geom_hline(yintercept = 0.7, linetype= 'dashed') + geom_vline(xintercept = 0.0, linetype= 'dashed') + stat_smooth(method = "lm", formula = y ~ poly(x, 1), se = TRUE,fullrange = FALSE, color= 'black', linetype= 'dashed') 

ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_offset_error_modelled_power_relationship.pdf', device = "pdf", width= 5, height =5)

# make boxplot 

ggplot(data2, aes(x=expon_error, y=corralphamodel))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("error in offset") + ylab("modelled alpha power")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = log10(0), linetype= 'dashed') + geom_hline(yintercept = 0.7, linetype= 'dashed') + geom_vline(xintercept = 0.0, linetype= 'dashed') + stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = TRUE,fullrange = FALSE, color= 'black', linetype= 'dashed') 

ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_expon_error_modelledpower_relationship.pdf', device = "pdf", width= 5, height =5)

ggplot(data2, aes(x=log10(abs(expon_error)), y=corralphamodel))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in exponent") + ylab("modelled alpha power")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = log10(0), linetype= 'dashed') + geom_hline(yintercept = 0.7, linetype= 'dashed') +  stat_smooth(method = "lm", formula = y ~ poly(x, 1), se = TRUE,fullrange = FALSE, color= 'black')  + coord_cartesian(xlim = c(-4, 0), ylim = c(0.1, 1.75))

ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_scatter_error_power_relationship_by_simulated_exponent.pdf', device = "pdf", width= 5, height =5)


ggplot(data2, aes(x=log10(abs(expon_error)), y=log10(corralphamodel)))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in exponent") + ylab("modelled power (log-log)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = log10(0), linetype= 'dashed') + geom_hline(yintercept = log10(0.7), linetype= 'dashed') +  stat_smooth(method = "lm", formula = y ~ poly(x, 1), se = TRUE,fullrange = FALSE, color= 'black')  + coord_cartesian(xlim = c(-4, 0), ylim = c(-0.7, 0.3))

ggsave('~/Desktop/alertness_2023/Figures/Simulated_exponent_scatter_error_MODELLED_power_relationship_by_simulated_exponent.pdf', device = "pdf", width= 5, height =5)

ggplot(data2[abs(data2$expon_error) < 0.05,], aes(x=corralphamodel, y=corralpha))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in exponent") + ylab("corrected alpha power (log-log)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = log10(0), linetype= 'dashed') + geom_hline(yintercept = 0.7, linetype= 'dashed') +  stat_smooth(method = "lm", formula = y ~ poly(x, 1), se = TRUE,fullrange = FALSE, color= 'black') 


ggplot(data2[abs(data2$expon_error) > 0.05,], aes(x=corralphamodel, y=corralpha))+  geom_point(shape=21, color="white",fill="#10A0C0", size=5, alpha=0.5) + theme_classic() + xlab("log 10 error in exponent") + ylab("corrected alpha power (log-log)")  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + geom_vline(xintercept = log10(0), linetype= 'dashed') + geom_hline(yintercept = 0.7, linetype= 'dashed') +  stat_smooth(method = "lm", formula = y ~ poly(x, 1), se = TRUE,fullrange = FALSE, color= 'black') 


DescTools::SpearmanRho(data2$corralpha[abs(data2$expon_error) > 0.05], data2$corralphamodel[abs(data2$expon_error) > 0.05], use = c("complete.obs"), conf.level = 0.95) 

DescTools::SpearmanRho(data2$corralpha[abs(data2$expon_error) < 0.05], data2$corralphamodel[abs(data2$expon_error) < 0.05], use = c("complete.obs"), conf.level = 0.95) 

datareg= as.data.frame(scale(data2))
lm1=lm(corralphamodel ~  corralpha , datareg)
lm2=lm(corralphamodel ~  corralpha +expon_error, datareg)
lm3=lm(corralphamodel ~  corralpha* expon_error, datareg)
anova(lm1,lm2,lm3)
BIC(lm3) - BIC(lm2)
sjPlot::tab_model(lm2)



spr1=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.6], rowMeans(corrspec2[data2$Var1==0.6,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr2=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.7], rowMeans(corrspec2[data2$Var1==0.7,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.8], rowMeans(corrspec2[data2$Var1==0.8,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.9], rowMeans(corrspec2[data2$Var1==0.9,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.0], rowMeans(corrspec2[data2$Var1==1.0,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.1], rowMeans(corrspec2[data2$Var1==1.1,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.2], rowMeans(corrspec2[data2$Var1==1.2,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.3], rowMeans(corrspec2[data2$Var1==1.3,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.4], rowMeans(corrspec2[data2$Var1==1.4,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr10=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.5], rowMeans(corrspec2[data2$Var1==1.5,22:36]), use = c("complete.obs"), conf.level = 0.95) 

data4plot=data.frame(freqs= c(0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5),
                     corrs=c(spr1[[1]], spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]], spr10[[1]]), 
                     lower=c(spr1[[2]], spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]], spr10[[2]]), 
                     upper=c(spr1[[3]], spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]], spr10[[3]]))


ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill='1')) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated arrhythmic slope (Hz-1)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')

lm00=lm(expon_BIC ~ corralpha*alpha_amplitude, data2)
summary(lm00)

data4plot2=data4plot

spr1=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.6], data2$corralphamodel[data2$Var1==0.6], use = c("complete.obs"), conf.level = 0.95) 
spr2=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.7], data2$corralphamodel[data2$Var1==0.7], use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.8], data2$corralphamodel[data2$Var1==0.8], use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.9], data2$corralphamodel[data2$Var1==0.9], use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.0], data2$corralphamodel[data2$Var1==1.0], use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.1], data2$corralphamodel[data2$Var1==1.1], use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.2], data2$corralphamodel[data2$Var1==1.2], use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.3], data2$corralphamodel[data2$Var1==1.3], use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.4], data2$corralphamodel[data2$Var1==1.4], use = c("complete.obs"), conf.level = 0.95) 
spr10=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.5], data2$corralphamodel[data2$Var1==1.5], use = c("complete.obs"), conf.level = 0.95) 


data4plot=data.frame(freqs= c(0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5),
                     corrs=c(spr1[[1]], spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]], spr10[[1]]), 
                     lower=c(spr1[[2]], spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]], spr10[[2]]), 
                     upper=c(spr1[[3]], spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]], spr10[[3]]),
                     nototals= c(sum(is.na(data2$corralphamodel[data2$Var1==0.6]))/length(data2$corralphamodel[data2$Var1==0.6]),
                                 sum(is.na(data2$corralphamodel[data2$Var1==0.7]))/length(data2$corralphamodel[data2$Var1==0.7]),
                                 sum(is.na(data2$corralphamodel[data2$Var1==0.8]))/length(data2$corralphamodel[data2$Var1==0.8]),sum(is.na(data2$corralphamodel[data2$Var1==0.9]))/length(data2$corralphamodel[data2$Var1==0.9]),
                     sum(is.na(data2$corralphamodel[data2$Var1==1]))/length(data2$corralphamodel[data2$Var1==1]),
                     sum(is.na(data2$corralphamodel[data2$Var1==1.1]))/length(data2$corralphamodel[data2$Var1==1.1]),
                     sum(is.na(data2$corralphamodel[data2$Var1==1.2]))/length(data2$corralphamodel[data2$Var1==1.2]),
                     sum(is.na(data2$corralphamodel[data2$Var1==1.3]))/length(data2$corralphamodel[data2$Var1==1.3]),
                     sum(is.na(data2$corralphamodel[data2$Var1==1.4]))/length(data2$corralphamodel[data2$Var1==1.4]),sum(is.na(data2$corralphamodel[data2$Var1==1.5]))/length(data2$corralphamodel[data2$Var1==1.5])))


data4plot$nototals= data4plot$nototals+0.000001
ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= -1*log10(100*nototals), fill= -1*log10(100*nototals))) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2()   + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14)) + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white")+ geom_point( size=5)
               
ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_alpha_slope_by_simulated_exponent.pdf', device = "pdf", height = 5, width = 5)

data4plot2$nototals =0
data4plot=rbind(data4plot2, data4plot)
data4plot$type= rep(c('subtraction', 'model'), each =10)

data4plot4=data4plot

data4plot$nototals= data4plot$nototals+0.000001
ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= -1*log10(100*nototals), fill= -1*log10(100*nototals))) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2()   + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14)) + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white")+ geom_point( size=5) + facet_wrap(~type) + geom_hline(yintercept = c(-0.15, 0.15), linetype= 'dashed')

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_alpha_slope_by_simulated_exponent_comparison_alpha_method.pdf', device = "pdf", height = 5, width = 12)



spr1=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.6], data2$corralphalinear[data2$Var1==0.6], use = c("complete.obs"), conf.level = 0.95) 
spr2=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.7], data2$corralphalinear[data2$Var1==0.7], use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.8], data2$corralphalinear[data2$Var1==0.8], use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==0.9], data2$corralphalinear[data2$Var1==0.9], use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.0], data2$corralphalinear[data2$Var1==1.0], use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.1], data2$corralphalinear[data2$Var1==1.1], use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.2], data2$corralphalinear[data2$Var1==1.2], use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.3], data2$corralphalinear[data2$Var1==1.3], use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.4], data2$corralphalinear[data2$Var1==1.4], use = c("complete.obs"), conf.level = 0.95) 
spr10=DescTools::SpearmanRho(data2$expon_BIC[data2$Var1==1.5], data2$corralphalinear[data2$Var1==1.5], use = c("complete.obs"), conf.level = 0.95) 


data4plot=data.frame(freqs= c(0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5),
                     corrs=c(spr1[[1]], spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]], spr10[[1]]), 
                     lower=c(spr1[[2]], spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]], spr10[[2]]), 
                     upper=c(spr1[[3]], spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]], spr10[[3]]))

ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill='1')) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated arrhythmic slope (Hz-1)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')




data4plot$nototals =0
data4plot$type = 'linear'
data4plot=rbind(data4plot4, data4plot)
data4plot$type = factor(data4plot$type, levels = c('model', 'subtraction', 'linear'))

ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill= '1')) +
    ggpubr::theme_classic2()   + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white")+ geom_point( size=5) + facet_wrap(~type) + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + geom_hline(yintercept = c(-0.15, 0.15), linetype= 'dashed')

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_alpha_slope_by_simulated_exponents_model_no_NAs_compare_all.pdf', device = "pdf", height = 5, width = 15)


## beta effects 

spr1=DescTools::SpearmanRho(data2$corrbetamodel[data2$Var1==0.6], data2$corralphamodel[data2$Var1==0.6], use = c("complete.obs"), conf.level = 0.95) 
spr2=DescTools::SpearmanRho(data2$corrbetamodel[data2$Var1==0.7], data2$corralphamodel[data2$Var1==0.7], use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$corrbetamodel[data2$Var1==0.8], data2$corralphamodel[data2$Var1==0.8], use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$corrbetamodel[data2$Var1==0.9], data2$corralphamodel[data2$Var1==0.9], use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$corrbetamodel[data2$Var1==1.0], data2$corralphamodel[data2$Var1==1.0], use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$corrbetamodel[data2$Var1==1.1], data2$corralphamodel[data2$Var1==1.1], use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$corrbetamodel[data2$Var1==1.2], data2$corralphamodel[data2$Var1==1.2], use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$corrbetamodel[data2$Var1==1.3], data2$corralphamodel[data2$Var1==1.3], use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$corrbetamodel[data2$Var1==1.4], data2$corralphamodel[data2$Var1==1.4], use = c("complete.obs"), conf.level = 0.95) 
spr10=DescTools::SpearmanRho(data2$corrbetamodel[data2$Var1==1.5], data2$corralphamodel[data2$Var1==1.5], use = c("complete.obs"), conf.level = 0.95) 


data4plot=data.frame(freqs= c(0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5),
                     corrs=c(spr1[[1]], spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]], spr10[[1]]), 
                     lower=c(spr1[[2]], spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]], spr10[[2]]), 
                     upper=c(spr1[[3]], spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]], spr10[[3]]))

ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill='1')) +
    ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated arrhythmic slope (Hz-1)") + ylab("estimated relationship with beta (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')

data4plot2= data4plot

spr1=DescTools::SpearmanRho(data2$corrbeta[data2$Var1==0.6], data2$corralpha[data2$Var1==0.6], use = c("complete.obs"), conf.level = 0.95) 
spr2=DescTools::SpearmanRho(data2$corrbeta[data2$Var1==0.7], data2$corralpha[data2$Var1==0.7], use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$corrbeta[data2$Var1==0.8], data2$corralpha[data2$Var1==0.8], use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$corrbeta[data2$Var1==0.9], data2$corralpha[data2$Var1==0.9], use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$corrbeta[data2$Var1==1.0], data2$corralpha[data2$Var1==1.0], use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$corrbeta[data2$Var1==1.1], data2$corralpha[data2$Var1==1.1], use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$corrbeta[data2$Var1==1.2], data2$corralpha[data2$Var1==1.2], use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$corrbeta[data2$Var1==1.3], data2$corralpha[data2$Var1==1.3], use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$corrbeta[data2$Var1==1.4], data2$corralpha[data2$Var1==1.4], use = c("complete.obs"), conf.level = 0.95) 
spr10=DescTools::SpearmanRho(data2$corrbeta[data2$Var1==1.5], data2$corralpha[data2$Var1==1.5], use = c("complete.obs"), conf.level = 0.95) 

data4plot=data.frame(freqs= c(0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5),
                     corrs=c(spr1[[1]], spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]], spr10[[1]]), 
                     lower=c(spr1[[2]], spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]], spr10[[2]]), 
                     upper=c(spr1[[3]], spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]], spr10[[3]]))

ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill='1')) +
    ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated arrhythmic slope (Hz-1)") + ylab("estimated relationship with beta (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')

data4plot3= data4plot


spr1=DescTools::SpearmanRho(data2$corrbetalinear[data2$Var1==0.6], data2$corralphalinear[data2$Var1==0.6], use = c("complete.obs"), conf.level = 0.95) 
spr2=DescTools::SpearmanRho(data2$corrbetalinear[data2$Var1==0.7], data2$corralphalinear[data2$Var1==0.7], use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$corrbetalinear[data2$Var1==0.8], data2$corralphalinear[data2$Var1==0.8], use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$corrbetalinear[data2$Var1==0.9], data2$corralphalinear[data2$Var1==0.9], use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$corrbetalinear[data2$Var1==1.0], data2$corralphalinear[data2$Var1==1.0], use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$corrbetalinear[data2$Var1==1.1], data2$corralphalinear[data2$Var1==1.1], use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$corrbetalinear[data2$Var1==1.2], data2$corralphalinear[data2$Var1==1.2], use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$corrbetalinear[data2$Var1==1.3], data2$corralphalinear[data2$Var1==1.3], use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$corrbetalinear[data2$Var1==1.4], data2$corralphalinear[data2$Var1==1.4], use = c("complete.obs"), conf.level = 0.95) 
spr10=DescTools::SpearmanRho(data2$corrbetalinear[data2$Var1==1.5], data2$corralphalinear[data2$Var1==1.5], use = c("complete.obs"), conf.level = 0.95) 

data4plot=data.frame(freqs= c(0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5),
                     corrs=c(spr1[[1]], spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]], spr10[[1]]), 
                     lower=c(spr1[[2]], spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]], spr10[[2]]), 
                     upper=c(spr1[[3]], spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]], spr10[[3]]))

ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill='1')) +
    ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated arrhythmic slope (Hz-1)") + ylab("estimated relationship with beta (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')


data4plot=rbind(data4plot, data4plot2, data4plot3)
data4plot$type = rep(c('linear', 'model', 'subtraction'), each=10)
data4plot$type = factor(data4plot$type, levels = c('model', 'subtraction', 'linear'))

ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill= '1')) +
    ggpubr::theme_classic2()   + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white")+ geom_point( size=5) + facet_wrap(~type) + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + geom_hline(yintercept = c( 0.15), linetype= 'dashed')

ggsave('~/Desktop/alertness_2023/Figures/Simulations_relationship_between_alpha_beta_by_simulated_exponents_model_compare_all.pdf', device = "pdf", height = 5, width = 15)




spr1=DescTools::SpearmanRho(data2$corrthetalinear[data2$Var1==0.6], data2$corrbetalinear[data2$Var1==0.6], use = c("complete.obs"), conf.level = 0.95) 
spr2=DescTools::SpearmanRho(data2$corrthetalinear[data2$Var1==0.7], data2$corrbetalinear[data2$Var1==0.7], use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$corrthetalinear[data2$Var1==0.8], data2$corrbetalinear[data2$Var1==0.8], use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$corrthetalinear[data2$Var1==0.9], data2$corrbetalinear[data2$Var1==0.9], use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$corrthetalinear[data2$Var1==1.0], data2$corrbetalinear[data2$Var1==1.0], use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$corrthetalinear[data2$Var1==1.1], data2$corrbetalinear[data2$Var1==1.1], use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$corrthetalinear[data2$Var1==1.2], data2$corrbetalinear[data2$Var1==1.2], use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$corrthetalinear[data2$Var1==1.3], data2$corrbetalinear[data2$Var1==1.3], use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$corrthetalinear[data2$Var1==1.4], data2$corrbetalinear[data2$Var1==1.4], use = c("complete.obs"), conf.level = 0.95) 
spr10=DescTools::SpearmanRho(data2$corrthetalinear[data2$Var1==1.5], data2$corrbetalinear[data2$Var1==1.5], use = c("complete.obs"), conf.level = 0.95) 

data4plot=data.frame(freqs= c(0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5),
                     corrs=c(spr1[[1]], spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]], spr10[[1]]), 
                     lower=c(spr1[[2]], spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]], spr10[[2]]), 
                     upper=c(spr1[[3]], spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]], spr10[[3]]))

ggplot(data4plot, aes(freqs, corrs, ymin= lower, ymax= upper, colour= '1', fill='1')) +
    ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated arrhythmic slope (Hz-1)") + ylab("estimated relationship with beta (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')



## offset 

spr1=DescTools::SpearmanRho(data2$offset_BIC[data2$Var1==0.6], rowMeans(corrspec2[data2$Var1==0.6,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr2=DescTools::SpearmanRho(data2$offset_BIC[data2$Var1==0.7], rowMeans(corrspec2[data2$Var1==0.7,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr3=DescTools::SpearmanRho(data2$offset_BIC[data2$Var1==0.8], rowMeans(corrspec2[data2$Var1==0.8,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr4=DescTools::SpearmanRho(data2$offset_BIC[data2$Var1==0.9], rowMeans(corrspec2[data2$Var1==0.9,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr5=DescTools::SpearmanRho(data2$offset_BIC[data2$Var1==1.0], rowMeans(corrspec2[data2$Var1==1.0,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr6=DescTools::SpearmanRho(data2$offset_BIC[data2$Var1==1.1], rowMeans(corrspec2[data2$Var1==1.1,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr7=DescTools::SpearmanRho(data2$offset_BIC[data2$Var1==1.2], rowMeans(corrspec2[data2$Var1==1.2,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr8=DescTools::SpearmanRho(data2$offset_BIC[data2$Var1==1.3], rowMeans(corrspec2[data2$Var1==1.3,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr9=DescTools::SpearmanRho(data2$offset_BIC[data2$Var1==1.4], rowMeans(corrspec2[data2$Var1==1.4,22:36]), use = c("complete.obs"), conf.level = 0.95) 
spr10=DescTools::SpearmanRho(data2$offset_BIC[data2$Var1==1.5], rowMeans(corrspec2[data2$Var1==1.5,22:36]), use = c("complete.obs"), conf.level = 0.95) 

data4plot=data.frame(freqs= c(0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5),
                     corrs=c(spr1[[1]], spr2[[1]], spr3[[1]], spr4[[1]], spr5[[1]], spr6[[1]], spr7[[1]], spr8[[1]], spr9[[1]], spr10[[1]]), 
                     lower=c(spr1[[2]], spr2[[2]], spr3[[2]], spr4[[2]], spr5[[2]], spr6[[2]], spr7[[2]], spr8[[2]], spr9[[2]], spr10[[2]]), 
                     upper=c(spr1[[3]], spr2[[3]], spr3[[3]], spr4[[3]], spr5[[3]], spr6[[3]], spr7[[3]], spr8[[3]], spr9[[3]], spr10[[3]]))

```





```{r simulated correlations exponents }
data= read.csv('~/Documents/McGill/simulations4Giu/Simulations_of_correlations_exponent_agerelationship_output.csv')

corrspec = read.csv('~/Documents/McGill/simulations4Giu/Simulations_of_correlations_exponent_agerelationship_corrspec.csv', header = FALSE)

data$expon_error= (data$exponsim-data$expon_BIC)^2

corrspecLinear= read.csv('~/Documents/McGill/simulations4Giu/Simulations_of_correlations_exponent_agerelationshipy_corrspec_linear.csv', header = FALSE)
data$corralpha=rowMeans(corrspec[,22:36])
data$corralphalinear=rowMeans(corrspecLinear[,22:36])

# add in column for beta even though we do not simulate changes 
data$corrbeta=rowMeans(corrspec[,37:73])
data$corrbetalinear=rowMeans(corrspecLinear[,37:73])

peak_params_cf= read.csv('~/Documents/McGill/simulations4Giu/Simulations_of_correlations_exponent_agerelationship_peaks_centerFreq.csv', header = FALSE)
peak_params_amp= read.csv('~/Documents/McGill/simulations4Giu/Simulations_of_correlations_exponent_agerelationship_peaks_amplitude.csv', header = FALSE)

peak_params_cf= as.matrix(peak_params_cf)
peak_params_amp= as.matrix(peak_params_amp)

peak_params_amp[which(peak_params_cf <5 | peak_params_cf >15)] = NaN
peak_params_cf[which(peak_params_cf <5 | peak_params_cf >15)] = NaN

data$corralphamodel=apply(peak_params_amp, 1,max,na.rm = TRUE)
data$corralphamodel[data$corralphamodel== -Inf] =NaN

DescTools::SpearmanRho(data$corralpha, data$corralphalinear, use = c("complete.obs"), conf.level = 0.95) # 0.6120972

DescTools::SpearmanRho(data$corralpha, data$corralphamodel, use = c("complete.obs"), conf.level = 0.95) # 0.4024242

DescTools::SpearmanRho(data$corralphalinear, data$corralphamodel, use = c("complete.obs"), conf.level = 0.95) # 0.4843084

DescTools::SpearmanRho(data$corralpha, data$expon_BIC, use = c("complete.obs"), conf.level = 0.95) # -0.067864147

DescTools::SpearmanRho(data$corralphalinear, data$expon_BIC, use = c("complete.obs"), conf.level = 0.95) # -0.0618230421

DescTools::SpearmanRho(data$corralphamodel, data$expon_BIC, use = c("complete.obs"), conf.level = 0.95) # -0.03325440

# remove bad estimates 
data2= data[abs(data$mse_BIC) < 3*sd(data$mse_BIC) + mean(data$mse_BIC) ,]

# for every simulated correlation what is the true effect size
count=1
effect=matrix(,nrow = 10, ncol = 3)
for (i in unique(data2$params)){
  temp = data2[data2$params==i,]
  effecttemp = DescTools::SpearmanRho(temp$age, temp$expon_BIC, use = c("complete.obs"), conf.level = 0.95) 
  print(mean(temp$mse_BIC_final))
  effect[count,1] = effecttemp[[1]]
  effect[count,2] = effecttemp[[2]]
  effect[count,3] = effecttemp[[3]]
  count=count+1
  
}

effect2= effect

count=1
effect=matrix(,nrow = 10, ncol = 3)
for (i in unique(data2$params)){
  temp = data2[data2$params==i,]
  effecttemp = DescTools::SpearmanRho(temp$exponsim, temp$expon_BIC, use = c("complete.obs"), conf.level = 0.95) 
  effect[count,1] = effecttemp[[1]]
  effect[count,2] = effecttemp[[2]]
  effect[count,3] = effecttemp[[3]]
  count=count+1
  
}

effect

effect_df= data.frame(effect2)
effect_df$effectsize= c(-0.0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9)
colnames(effect_df) = c('correlation', 'lower', 'upper', 'effectsize')
tt= data2 %>% group_by(params) %>% summarise(mean(mse_BIC_final))
effect_df$mse = c(tt[,2])$`mean(mse_BIC_final)`

lm0=lm(mse ~ effectsize, effect_df)
summary(lm0)

#ggplot(effect_df, aes(correlation, effectsize, xmin= lower, xmax= upper, colour= '1', fill='1')) +  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("estimated relationship (r)") + ylab("simulated relationship (r)") + geom_segment(aes(x =effectsize,xend=effectsize, y=effectsize, yend=Inf), linetype="dashed", color = "grey", size=0.5) + geom_point( aes(effectsize, effectsize),colour= "grey", size=2 )+ geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + scale_y_reverse() + scale_x_reverse()

ggplot(effect_df, aes(correlation, effectsize, xmin= lower, xmax= upper, colour= '1', fill='1')) +  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("estimated relationship (r)") + ylab("simulated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( aes(effectsize, effectsize),colour= "white", size=4 )+ geom_point( aes(effectsize, effectsize),colour= "grey", size=3 )+ geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + scale_y_reverse() + scale_x_reverse()

ggsave('~/Desktop/alertness_2023/Figures/Simulated_relationship_expon_age.pdf', device = "pdf", height = 5, width = 5)



effect_df= data.frame(effect)
effect_df$effectsize= c(-0.0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9)
colnames(effect_df) = c('correlation', 'lower', 'upper', 'effectsize')
tt= data2 %>% group_by(params) %>% summarise(mean(mse_BIC_final))
effect_df$mse = c(tt[,2])$`mean(mse_BIC_final)`

lm0=lm(mse ~ effectsize, effect_df)
summary(lm0)

ggplot(effect_df, aes(correlation, effectsize, xmin= lower, xmax= upper, colour= '1', fill='1')) +  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("estimated relationship (r)") + ylab("simulated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')

ggsave('~/Desktop/alertness_2023/Figures/Simulated_relationship_expon_age.pdf', device = "pdf", height = 5, width = 5)

# plot his relationship 
cor.test(effect_df$effectsize- effect_df$correlation, effect[,1], method = 'spearman')

data4plot= data.frame(error_in_estimate= effect_df$effectsize- effect_df$correlation, relationship_bw_sim_true= effect[,1])

ggplot(data4plot, aes(error_in_estimate, relationship_bw_sim_true, colour= '1', fill='1')) +
  stat_smooth( method = "glm",formula = y ~ poly(x, 1),fullrange = T, color= 'black')+  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("simulated rhythmic alpha frequency (Hz)") + ylab("estimated relationship (r)") +  geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')



```






```{r simulated correlations amplitude alpha }
data= read.csv('~/Documents/McGill/simulations4Giu/Simulations_of_correlations_alphalow2_agerelationship_output.csv')

corrspec = read.csv('~/Documents/McGill/simulations4Giu/Simulations_of_correlations_alphalow2_agerelationship_corrspec.csv', header = FALSE)

data$expon_error= (1-data$expon_BIC)^2

corrspecLinear= read.csv('~/Documents/McGill/simulations4Giu/Simulations_of_correlations_alphalow2_agerelationshipy_corrspec_linear.csv', header = FALSE)
data$corralpha=rowMeans(corrspec[,22:36])
data$corralphalinear=rowMeans(corrspecLinear[,22:36])

# add in column for beta even though we do not simulate changes 
data$corrbeta=rowMeans(corrspec[,37:73])
data$corrbetalinear=rowMeans(corrspecLinear[,37:73])

peak_params_cf= read.csv('~/Documents/McGill/simulations4Giu/Simulations_of_correlations_alphalow2_agerelationship_peaks_centerFreq.csv', header = FALSE)
peak_params_amp= read.csv('~/Documents/McGill/simulations4Giu/Simulations_of_correlations_alphalow2_agerelationship_peaks_amplitude.csv', header = FALSE)

peak_params_cf= as.matrix(peak_params_cf)
peak_params_amp= as.matrix(peak_params_amp)

peak_params_amp[which(peak_params_cf <5 | peak_params_cf >15)] = NaN
peak_params_cf[which(peak_params_cf <5 | peak_params_cf >15)] = NaN

data$corralphamodel=apply(peak_params_amp, 1,max,na.rm = TRUE)
data$corralphamodel[data$corralphamodel== -Inf] =NaN

DescTools::SpearmanRho(data$corralpha, data$corralphalinear, use = c("complete.obs"), conf.level = 0.95) # 0.8796040

DescTools::SpearmanRho(data$corralpha, data$corralphamodel, use = c("complete.obs"), conf.level = 0.95) # 0.7720022

DescTools::SpearmanRho(data$corralphalinear, data$corralphamodel, use = c("complete.obs"), conf.level = 0.95) #0.8336679

DescTools::SpearmanRho(data$corralpha, data$expon_BIC, use = c("complete.obs"), conf.level = 0.95) # -0.054664801

DescTools::SpearmanRho(data$corralphalinear, data$expon_BIC, use = c("complete.obs"), conf.level = 0.95) # -0.04408099

DescTools::SpearmanRho(data$corralphamodel, data$expon_BIC, use = c("complete.obs"), conf.level = 0.95) # -0.004084832

# remove bad estimates 
data2= data[abs(data$mse_BIC) < 3*sd(data$mse_BIC) + mean(data$mse_BIC) ,]

# for every simulated correlation what is the true effect size
count=1
effect=matrix(,nrow = 10, ncol = 3)
for (i in unique(data2$params)){
  temp = data2[data2$params==i,]
  effecttemp = DescTools::SpearmanRho(temp$age, temp$corralpha, use = c("complete.obs"), conf.level = 0.95) 
  print(mean(temp$mse_BIC_final))
  effect[count,1] = effecttemp[[1]]
  effect[count,2] = effecttemp[[2]]
  effect[count,3] = effecttemp[[3]]
  count=count+1
  
}

effect

count=1
effect2=matrix(,nrow = 10, ncol = 3)
for (i in unique(data2$params)){
  temp = data2[data2$params==i,]
  effecttemp = DescTools::SpearmanRho(temp$exponsim, temp$corralpha, use = c("complete.obs"), conf.level = 0.95) 
  effect2[count,1] = effecttemp[[1]]
  effect2[count,2] = effecttemp[[2]]
  effect2[count,3] = effecttemp[[3]]
  count=count+1
  
}


effect_df= data.frame(effect)
effect_df$effectsize= c(-0.0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9)
colnames(effect_df) = c('correlation', 'lower', 'upper', 'effectsize')
tt= data2 %>% group_by(params) %>% summarise(mean(mse_BIC_final))
effect_df$mse = c(tt[,2])$`mean(mse_BIC_final)`

lm0=lm(mse ~ effectsize, effect_df)
summary(lm0)

ggplot(effect_df, aes(correlation, effectsize, xmin= lower, xmax= upper, colour= '1', fill='1')) +  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("estimated relationship (r)") + ylab("simulated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( aes(effectsize, effectsize),colour= "white", size=4 )+ geom_point( aes(effectsize, effectsize),colour= "grey", size=3 )+ geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + scale_y_reverse() + scale_x_reverse()

ggsave('~/Desktop/alertness_2023/Figures/Simulated_relationship_alphalowamp2_age.pdf', device = "pdf", height = 5, width = 5)



effect_df= data.frame(effect2)
effect_df$effectsize= c(-0.0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9)
colnames(effect_df) = c('correlation', 'lower', 'upper', 'effectsize')
tt= data2 %>% group_by(params) %>% summarise(mean(mse_BIC_final))
effect_df$mse = c(tt[,2])$`mean(mse_BIC_final)`

lm0=lm(mse ~ effectsize, effect_df)
summary(lm0)

ggplot(effect_df, aes(correlation, effectsize, xmin= lower, xmax= upper, colour= '1', fill='1')) +  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("estimated relationship (r)") + ylab("simulated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none')

ggsave('~/Desktop/alertness_2023/Figures/Simulated_relationship_alphalowamp2_tosimulation.pdf', device = "pdf", height = 5, width = 5)



# for every simulated correlation what is the true effect size
count=1
effect=matrix(,nrow = 10, ncol = 3)
for (i in unique(data2$params)){
  temp = data2[data2$params==i,]
  effecttemp = DescTools::SpearmanRho(temp$age, temp$corralphalinear, use = c("complete.obs"), conf.level = 0.95) 
  effect[count,1] = effecttemp[[1]]
  effect[count,2] = effecttemp[[2]]
  effect[count,3] = effecttemp[[3]]
  count=count+1
  
}

effect_df= data.frame(effect)
effect_df$effectsize= c(-0.0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9)
colnames(effect_df) = c('correlation', 'lower', 'upper', 'effectsize')
tt= data2 %>% group_by(params) %>% summarise(mean(mse_BIC_final))
effect_df$mse = c(tt[,2])$`mean(mse_BIC_final)`

ggplot(effect_df, aes(correlation, effectsize, xmin= lower, xmax= upper, colour= '1', fill='1')) +  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("estimated relationship (r)") + ylab("simulated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( aes(effectsize, effectsize),colour= "white", size=4 )+ geom_point( aes(effectsize, effectsize),colour= "grey", size=3 )+ geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + scale_y_reverse() + scale_x_reverse()

ggsave('~/Desktop/alertness_2023/Figures/Simulated_relationship_alphalowamp2_age_corrlinearspace.pdf', device = "pdf", height = 5, width = 5)


# for every simulated correlation what is the true effect size
count=1
effect=matrix(,nrow = 10, ncol = 4)
for (i in unique(data2$params)){
  temp = data2[data2$params==i,]
  effecttemp = DescTools::SpearmanRho(temp$age, temp$corralphamodel, use = c("complete.obs"), conf.level = 0.95) 
  effect[count,1] = effecttemp[[1]]
  effect[count,2] = effecttemp[[2]]
  effect[count,3] = effecttemp[[3]]
  effect[count,4] = sum(is.na(temp$corralphamodel))/100
  count=count+1
  
}

effect_df= data.frame(effect)
effect_df$effectsize= c(-0.0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9)
colnames(effect_df) = c('correlation', 'lower', 'upper', 'nacount','effectsize')
tt= data2 %>% group_by(params) %>% summarise(mean(mse_BIC_final))
effect_df$mse = c(tt[,2])$`mean(mse_BIC_final)`

ggplot(effect_df, aes(correlation, effectsize, xmin= lower, xmax= upper, colour= nacount, fill=nacount)) +  ggpubr::theme_classic2()  + xlab("estimated relationship (r)") + ylab("simulated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( aes(effectsize, effectsize),colour= "white", size=4 )+ geom_point( aes(effectsize, effectsize),colour= "grey", size=3 )+ geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14)) + scale_y_reverse() + scale_x_reverse() + viridis::scale_color_viridis(option= 'mako', limits= c(0, 0.3), direction = -1) + viridis::scale_fill_viridis(option= 'mako', limits= c(0, 0.3), direction = -1)

ggsave('~/Desktop/alertness_2023/Figures/Simulated_relationship_alphalowamp2_age_corrmodel.pdf', device = "pdf", height = 5, width = 6)


data2$corralphamodel[is.na(data2$corralphamodel)] =0
# for every simulated correlation what is the true effect size
count=1
effect=matrix(,nrow = 10, ncol = 3)
for (i in unique(data2$params)){
  temp = data2[data2$params==i,]
  effecttemp = DescTools::SpearmanRho(temp$age, temp$corralphalinear, use = c("complete.obs"), conf.level = 0.95) 
  effect[count,1] = effecttemp[[1]]
  effect[count,2] = effecttemp[[2]]
  effect[count,3] = effecttemp[[3]]
  count=count+1
  
}

effect_df= data.frame(effect)
effect_df$effectsize= c(-0.0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9)
colnames(effect_df) = c('correlation', 'lower', 'upper', 'effectsize')
tt= data2 %>% group_by(params) %>% summarise(mean(mse_BIC_final))
effect_df$mse = c(tt[,2])$`mean(mse_BIC_final)`

ggplot(effect_df, aes(correlation, effectsize, xmin= lower, xmax= upper, colour= '1', fill='1')) +  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("estimated relationship (r)") + ylab("simulated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( aes(effectsize, effectsize),colour= "white", size=4 )+ geom_point( aes(effectsize, effectsize),colour= "grey", size=3 )+ geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + scale_y_reverse() + scale_x_reverse()

ggsave('~/Desktop/alertness_2023/Figures/Simulated_relationship_alphalowamp2_age_corrmodel_noNAN.pdf', device = "pdf", height = 5, width = 5)

```




```{r simulated correlations expon & alpha }
data= read.csv('~/Documents/McGill/simulations4Giu/Simulations_of_correlations_exponalphacorr_agerelationship_output.csv')

corrspec = read.csv('~/Documents/McGill/simulations4Giu/Simulations_of_correlations_exponalphacorr_agerelationship_corrspec.csv', header = FALSE)

data$expon_error= (1-data$expon_BIC)^2

corrspecLinear= read.csv('~/Documents/McGill/simulations4Giu/Simulations_of_correlations_exponalphacorr_agerelationshipy_corrspec_linear.csv', header = FALSE)
data$corralpha=rowMeans(corrspec[,22:36])
data$corralphalinear=rowMeans(corrspecLinear[,22:36])

# add in column for beta even though we do not simulate changes 
data$corrbeta=rowMeans(corrspec[,37:73])
data$corrbetalinear=rowMeans(corrspecLinear[,37:73])

peak_params_cf= read.csv('~/Documents/McGill/simulations4Giu/Simulations_of_correlations_exponalphacorr_agerelationship_peaks_centerFreq.csv', header = FALSE)
peak_params_amp= read.csv('~/Documents/McGill/simulations4Giu/Simulations_of_correlations_exponalphacorr_agerelationship_peaks_amplitude.csv', header = FALSE)

peak_params_cf= as.matrix(peak_params_cf)
peak_params_amp= as.matrix(peak_params_amp)

peak_params_amp[which(peak_params_cf <5 | peak_params_cf >15)] = NaN
peak_params_cf[which(peak_params_cf <5 | peak_params_cf >15)] = NaN

data$corralphamodel=apply(peak_params_amp, 1,max,na.rm = TRUE)
data$corralphamodel[data$corralphamodel== -Inf] =NaN

# remove bad estimates 
data2= data[abs(data$mse_BIC) < 3*sd(data$mse_BIC) + mean(data$mse_BIC) ,]

# for every simulated correlation what is the true effect size
count=1
effect=matrix(,nrow = 10, ncol = 3)
for (i in unique(data2$params)){
  temp = data2[data2$params==i,]
  effecttemp = DescTools::SpearmanRho(temp$expon_BIC_final, temp$corralpha, use = c("complete.obs"), conf.level = 0.95) 
  print(mean(temp$mse_BIC_final))
  effect[count,1] = effecttemp[[1]]
  effect[count,2] = effecttemp[[2]]
  effect[count,3] = effecttemp[[3]]
  count=count+1
  
}


effect_df= data.frame(effect)
effect_df$effectsize= c(-0.0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9)
colnames(effect_df) = c('correlation', 'lower', 'upper', 'effectsize')
tt= data2 %>% group_by(params) %>% summarise(mean(mse_BIC_final))
effect_df$mse = c(tt[,2])$`mean(mse_BIC_final)`

lm0=lm(mse ~ effectsize, effect_df)
summary(lm0)

ggplot(effect_df, aes(correlation, effectsize, xmin= lower, xmax= upper, colour= '1', fill='1')) +  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("estimated relationship (r)") + ylab("simulated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( aes(effectsize, effectsize),colour= "white", size=4 )+ geom_point( aes(effectsize, effectsize),colour= "grey", size=3 )+ geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + scale_y_reverse() + scale_x_reverse()

ggsave('~/Desktop/alertness_2023/Figures/Simulated_relationship_exponalphacorr_age.pdf', device = "pdf", height = 5, width = 5)


# for every simulated correlation what is the true effect size
count=1
effect=matrix(,nrow = 10, ncol = 3)
for (i in unique(data2$params)){
  temp = data2[data2$params==i,]
  effecttemp = DescTools::SpearmanRho(temp$expon_BIC_final, temp$corralphalinear, use = c("complete.obs"), conf.level = 0.95) 
  effect[count,1] = effecttemp[[1]]
  effect[count,2] = effecttemp[[2]]
  effect[count,3] = effecttemp[[3]]
  count=count+1
  
}

effect_df= data.frame(effect)
effect_df$effectsize= c(-0.0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9)
colnames(effect_df) = c('correlation', 'lower', 'upper', 'effectsize')
tt= data2 %>% group_by(params) %>% summarise(mean(mse_BIC_final))
effect_df$mse = c(tt[,2])$`mean(mse_BIC_final)`

ggplot(effect_df, aes(correlation, effectsize, xmin= lower, xmax= upper, colour= '1', fill='1')) +  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("estimated relationship (r)") + ylab("simulated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( aes(effectsize, effectsize),colour= "white", size=4 )+ geom_point( aes(effectsize, effectsize),colour= "grey", size=3 )+ geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + scale_y_reverse() + scale_x_reverse()

ggsave('~/Desktop/alertness_2023/Figures/Simulated_relationship_exponalphacorr_age_corrlinearspace.pdf', device = "pdf", height = 5, width = 5)


# for every simulated correlation what is the true effect size
count=1
effect=matrix(,nrow = 10, ncol = 4)
for (i in unique(data2$params)){
  temp = data2[data2$params==i,]
  effecttemp = DescTools::SpearmanRho(temp$expon_BIC_final, temp$corralphamodel, use = c("complete.obs"), conf.level = 0.95) 
  effect[count,1] = effecttemp[[1]]
  effect[count,2] = effecttemp[[2]]
  effect[count,3] = effecttemp[[3]]
  effect[count,4] = sum(is.na(temp$corralphamodel))/100
  count=count+1
  
}

effect_df= data.frame(effect)
effect_df$effectsize= c(-0.0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9)
colnames(effect_df) = c('correlation', 'lower', 'upper', 'nacount','effectsize')
tt= data2 %>% group_by(params) %>% summarise(mean(mse_BIC_final))
effect_df$mse = c(tt[,2])$`mean(mse_BIC_final)`

ggplot(effect_df, aes(correlation, effectsize, xmin= lower, xmax= upper, colour= nacount, fill=nacount)) +  ggpubr::theme_classic2()  + xlab("estimated relationship (r)") + ylab("simulated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( aes(effectsize, effectsize),colour= "white", size=4 )+ geom_point( aes(effectsize, effectsize),colour= "grey", size=3 )+ geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14)) + scale_y_reverse() + scale_x_reverse() + viridis::scale_color_viridis(option= 'mako', limits= c(0, 0.3), direction = -1) + viridis::scale_fill_viridis(option= 'mako', limits= c(0, 0.3), direction = -1)

ggsave('~/Desktop/alertness_2023/Figures/Simulated_relationship_exponalphacorr_age_corrmodel.pdf', device = "pdf", height = 5, width = 6)


data2$corralphamodel[is.na(data2$corralphamodel)] =0
# for every simulated correlation what is the true effect size
count=1
effect=matrix(,nrow = 10, ncol = 3)
for (i in unique(data2$params)){
  temp = data2[data2$params==i,]
  effecttemp = DescTools::SpearmanRho(temp$expon_BIC_final, temp$corralphamodel, use = c("complete.obs"), conf.level = 0.95) 
  effect[count,1] = effecttemp[[1]]
  effect[count,2] = effecttemp[[2]]
  effect[count,3] = effecttemp[[3]]
  count=count+1
  
}

effect_df= data.frame(effect)
effect_df$effectsize= c(-0.0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9)
colnames(effect_df) = c('correlation', 'lower', 'upper', 'effectsize')
tt= data2 %>% group_by(params) %>% summarise(mean(mse_BIC_final))
effect_df$mse = c(tt[,2])$`mean(mse_BIC_final)`

ggplot(effect_df, aes(correlation, effectsize, xmin= lower, xmax= upper, colour= '1', fill='1')) +  ggpubr::theme_classic2() + scale_fill_manual(values=c('#10A0C0', '#D97D08')) + scale_colour_manual(values=c('#10A0C0', '#D97D08')) + xlab("estimated relationship (r)") + ylab("simulated relationship (r)") + geom_errorbar(width=0)+geom_point(size=6, colour= "white") + geom_point( aes(effectsize, effectsize),colour= "white", size=4 )+ geom_point( aes(effectsize, effectsize),colour= "grey", size=3 )+ geom_point( size=5) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), axis.title.x = element_text(size=14), legend.position = 'none') + scale_y_reverse() + scale_x_reverse()

ggsave('~/Desktop/alertness_2023/Figures/Simulated_relationship_exponalphacorr_age_corrmodel_noNAN.pdf', device = "pdf", height = 5, width = 5)

```


